// AUTOGENERATED — do not edit by hand.
//
// Generated from `nexo-tool-meta` `#[ts(export)]` structs by
// `proyecto/scripts/regen-ts-types.sh`. The CI lint
// `proyecto/scripts/lint-ts-types-sync.sh` ensures this file
// matches the current Rust sources at HEAD; if it doesn't,
// regenerate via:
//
//   cd proyecto && bash scripts/regen-ts-types.sh
//
// Source of truth: `proyecto/crates/tool-meta/src/`.

/**
 * Recursive JSON value type — mirrors `serde_json::Value` on the
 * Rust side. ts-rs would normally emit a separate file for this;
 * we inline it here so the single-file `types.gen.ts` is
 * self-contained.
 */
export type JsonValue =
  | null
  | boolean
  | number
  | string
  | JsonValue[]
  | { [key: string]: JsonValue };

// ─── AdminAuditResult.ts ────────────────────────────────────

/**
 * Outcome of an admin RPC dispatch — written to the audit table
 * alongside every call.
 */
export type AdminAuditResult = "ok" | "error" | "denied";

// ─── AdminAuditRow.ts ────────────────────────────────────

/**
 * One row of `microapp_admin_audit`. Stable wire shape — every
 * field is present in the JSON payload returned by
 * `nexo/admin/microapp_audit/tail`.
 */
export type AdminAuditRow = { 
/**
 * Microapp identity (extension id from `extensions.yaml`).
 */
microapp_id: string, 
/**
 * Full JSON-RPC method (`nexo/admin/<domain>/<method>`).
 */
method: string, 
/**
 * Required capability (e.g. `agents_crud`). When the call
 * was denied, this is the capability that was missing.
 */
capability: string, 
/**
 * SHA-256 of canonicalised params (sorted keys). Lets
 * operators detect repeated identical calls without storing
 * PII payloads.
 */
args_hash: string, 
/**
 * Epoch milliseconds when dispatch started.
 */
started_at_ms: number, 
/**
 * `"ok"` | `"error"` | `"denied"`.
 */
result: AdminAuditResult, 
/**
 * Wall-clock duration of the dispatch.
 */
duration_ms: number, 
/**
 * Phase 83.8.12.7 — tenant scope for the call. Sniffed from
 * `params.tenant_id` (string) when present; legacy rows /
 * non-tenant-scoped calls (echo, pairing, credentials)
 * leave it `null`.
 */
tenant_id?: string | null, };

// ─── AgentEventKind.ts ────────────────────────────────────

/**
 * Discriminated event variant. v0 only emits
 * `TranscriptAppended`. Other slots are reserved enum entries
 * surfaced when the corresponding agent kind ships.
 */
export type AgentEventKind = { "kind": "transcript_appended", 
/**
 * Owning agent.
 */
agent_id: string, 
/**
 * Conversation scope.
 */
session_id: string, 
/**
 * Monotonic sequence within `session_id` — equal to the
 * 0-based index of the entry in the session's JSONL.
 */
seq: number, 
/**
 * Speaker role.
 */
role: TranscriptRole, 
/**
 * Redacted body (PII replaced with `[REDACTED:label]`).
 */
body: string, 
/**
 * Epoch milliseconds when the entry was recorded.
 */
sent_at_ms: number, 
/**
 * Opaque external sender id when applicable (channel
 * user id, peer agent id, …).
 */
sender_id?: string | null, 
/**
 * Channel/plugin that produced or received the entry
 * (e.g. `whatsapp`, `telegram`, `internal`).
 */
source_plugin: string, 
/**
 * Phase 83.8.12 — owning tenant. `None` for agents
 * predating multi-tenant. Firehose subscribers filter
 * on this without re-querying agents.yaml.
 */
tenant_id?: string | null, } | { "kind": "pending_inbounds_dropped", 
/**
 * Owning agent.
 */
agent_id: string, 
/**
 * Scope under which the drop happened. Carried whole
 * (rather than just `(channel, account_id, contact_id)`)
 * so future scope variants stay forward-compatible.
 */
scope: ProcessingScope, 
/**
 * Number of pending inbounds evicted by THIS push.
 */
dropped: number, 
/**
 * Epoch ms when the eviction happened.
 */
at_ms: number, } | { "kind": "escalation_requested", 
/**
 * Owning agent.
 */
agent_id: string, 
/**
 * Scope of the work item the agent is escalating.
 */
scope: ProcessingScope, 
/**
 * Free-form summary the agent supplied (already capped
 * to 500 chars by the admin handler before emit).
 */
summary: string, 
/**
 * Closed-enum reason for the escalation.
 */
reason: EscalationReason, 
/**
 * Operator hint on how aggressively to surface.
 */
urgency: EscalationUrgency, 
/**
 * Epoch ms when the agent raised the request.
 */
requested_at_ms: number, 
/**
 * Phase 83.8.12 — owning tenant; `None` for legacy /
 * single-tenant deployments. Firehose subscribers route
 * per-tenant without re-querying `agents.yaml`.
 */
tenant_id?: string | null, } | { "kind": "escalation_resolved", 
/**
 * Owning agent.
 */
agent_id: string, 
/**
 * Scope that was settled. Same value the `Pending`
 * emit carried.
 */
scope: ProcessingScope, 
/**
 * Epoch ms when the resolution happened.
 */
resolved_at_ms: number, 
/**
 * How the escalation was settled.
 */
by: ResolvedBy, 
/**
 * Phase 83.8.12 — owning tenant. Mirrors the
 * `Requested` shape so the pair stays
 * shape-symmetrical.
 */
tenant_id?: string | null, } | { "kind": "processing_state_changed", 
/**
 * Owning agent (denormalised from `scope` so subscribers
 * filter without parsing the discriminator).
 */
agent_id: string, 
/**
 * Scope whose state flipped.
 */
scope: ProcessingScope, 
/**
 * State observed immediately before the transition.
 */
prev_state: ProcessingControlState, 
/**
 * State the handler installed.
 */
new_state: ProcessingControlState, 
/**
 * Epoch ms when the transition happened.
 */
at_ms: number, 
/**
 * Phase 83.8.12 — owning tenant. `None` for legacy /
 * single-tenant deployments.
 */
tenant_id?: string | null, } | { "kind": "security_event", } & ({ "security_kind": "token_rotated", 
/**
 * Epoch milliseconds when the rotation persisted.
 */
at_ms: number, 
/**
 * Previous operator-token-hash (16-char sha256-hex
 * prefix). Zeroed (`""`) for the very first rotation
 * after boot when no prior hash is in cache.
 */
prev_hash: string, 
/**
 * New operator-token-hash.
 */
new_hash: string, 
/**
 * Optional operator-supplied audit hint, capped to
 * `auth::REASON_MAX_LEN` chars by the handler.
 */
reason?: string | null, }) | { "kind": "peer_typing", 
/**
 * Channel that produced the presence signal
 * (e.g. `whatsapp`).
 */
channel: string, 
/**
 * Channel-instance qualifier (e.g. `smoketest`). Empty
 * when the channel does not support multi-instance.
 */
account_id: string, 
/**
 * Channel-native sender id (e.g.
 * `573154645370@s.whatsapp.net`).
 */
sender_id: string, 
/**
 * `true` = peer is currently typing (composing).
 * `false` = peer stopped typing (paused).
 */
composing: boolean, 
/**
 * Epoch ms when the plugin observed the presence change.
 */
at_ms: number, 
/**
 * Owning agent when the plugin can resolve which agent
 * the conversation belongs to (single-agent inbound
 * binding). `None` for multi-agent setups — operator
 * dashboards then match by `(channel, account_id,
 * sender_id)` against every conversation.
 */
agent_id?: string | null, 
/**
 * Phase 83.8.12 — owning tenant. `None` for legacy /
 * single-tenant deployments.
 */
tenant_id?: string | null, } | { "kind": "whatsapp_bot_message", 
/**
 * WhatsApp plugin instance label (`smoketest`,
 * `default`, …). Resolves to the paired account.
 */
instance: string, 
/**
 * Bot JID, e.g. `718584497008509@bot`.
 */
bot_jid: string, 
/**
 * This chunk's stanza id (different per chunk).
 */
msg_id: string, 
/**
 * The original outbound id we sent to the bot. Constant
 * across every chunk of one logical reply.
 */
target_id: string, 
/**
 * `first` / `inner` / `last`. `last` = reply complete.
 */
edit: string, 
/**
 * Concatenated `AIRichResponseMessage.submessages[].messageText`
 * for this snapshot.
 */
text: string, 
/**
 * Epoch ms when the daemon received the chunk.
 */
at_ms: number, };

// ─── AuditTailFilter.ts ────────────────────────────────────

/**
 * Filter passed to `nexo/admin/microapp_audit/tail`. Every
 * field optional; combine to narrow the result set.
 */
export type AuditTailFilter = { 
/**
 * Restrict to a single microapp.
 */
microapp_id?: string | null, 
/**
 * Restrict to one JSON-RPC method.
 */
method?: string | null, 
/**
 * Restrict to one outcome.
 */
result?: AdminAuditResult | null, 
/**
 * Restrict to one tenant.
 */
tenant_id?: string | null, 
/**
 * Lower-bound timestamp (epoch ms). Use
 * `now - duration_ms` for human-friendly windows
 * ("last 24h", "last 7d", …).
 */
since_ms?: number | null, 
/**
 * Max rows to return. Server clamps to `[1, 500]`. `0` →
 * default 50.
 */
limit: number, 
/**
 * Pagination offset. `0` for the first page; subsequent
 * pages set this to the previous response's `next_offset`.
 */
offset: number, };

// ─── AuditTailPage.ts ────────────────────────────────────

/**
 * Paginated response for `nexo/admin/microapp_audit/tail`.
 * Frontend stores `entries`, appends on `loadMore` until
 * `has_more = false`.
 */
export type AuditTailPage = { 
/**
 * Rows in newest-first order, capped by `filter.limit`.
 */
entries: Array<AdminAuditRow>, 
/**
 * Total matching rows (without `limit`/`offset`). Useful
 * for "showing N of M" UI labels.
 */
total: number, 
/**
 * `true` when `entries.len()` was capped by `limit` and
 * more rows match the filter.
 */
has_more: boolean, 
/**
 * Offset to pass to the next call's `filter.offset`.
 * `None` when `has_more = false`.
 */
next_offset?: number | null, };

// ─── BindingContext.ts ────────────────────────────────────

/**
 * Identifies which inbound binding a tool call originated from.
 *
 * Stamped on every tool call dispatched to a Phase 11 stdio
 * extension or a Phase 12 MCP server (under `params._meta.nexo.binding`).
 * A microapp reads it to route work to the correct tenant /
 * channel / account.
 *
 * `binding_id` is rendered as `<channel>:<account_id|"default">`
 * — a stable identifier that survives `agents.yaml` reloads
 * (does NOT depend on the binding vector index).
 *
 * `mcp_channel_source` is populated when the inbound that
 * triggered the call arrived via a Phase 80.9 MCP channel
 * server (`"slack"`, `"telegram"`, etc.), allowing a tool to
 * distinguish "telegram-binding answered via MCP slack server"
 * from "telegram-binding answered via the native Telegram
 * plugin" while still seeing the same `(channel, account_id)`
 * tuple.
 *
 * # Example
 *
 * ```
 * use nexo_tool_meta::BindingContext;
 *
 * let ctx = BindingContext::agent_only("ana");
 * assert_eq!(ctx.agent_id, "ana");
 * assert!(ctx.channel.is_none());
 * ```
 */
export type BindingContext = { 
/**
 * Stable agent identifier (`agents.yaml.<id>`).
 */
agent_id: string, 
/**
 * Active session UUID. `None` outside an LLM turn (heartbeat
 * bootstrap, delegation receive, tests).
 */
session_id: string | null, 
/**
 * Channel name as declared in `InboundBinding.plugin`
 * (`"whatsapp"`, `"telegram"`, `"email"`, `"web"`, …).
 * `None` for contexts without a binding match.
 */
channel: string | null, 
/**
 * Account / instance discriminator from
 * `InboundBinding.instance`. `None` when the binding
 * declared no instance (single-account default).
 */
account_id: string | null, 
/**
 * Stable binding identifier rendered as
 * `<channel>:<account_id|"default">`. `None` for
 * bindingless contexts.
 */
binding_id: string | null, 
/**
 * Phase 80.9 — MCP channel server name when the inbound
 * arrived via `notifications/nexo/channel`. `None` for
 * native-channel inbounds. Examples: `"slack"`,
 * `"telegram"`, `"imessage"`.
 */
mcp_channel_source: string | null, 
/**
 * Phase 82.4 — event-subscriber metadata when the agent's
 * inbound was synthesised from a NATS event (subject pattern
 * match). `None` for human-message turns / native-channel
 * inbounds.
 */
event_source: EventSourceMeta | null, 
/**
 * Phase 83.8.12 — SaaS tenant (tenant) key. `None` for
 * agents that predate the multi-tenant model
 * (`agents.yaml.<id>` without an `tenant_id` field).
 * Multi-tenant filtering across admin RPC + microapp tools
 * keys on this field. Sits ABOVE `account_id`, which
 * remains the channel-side discriminator.
 */
tenant_id?: string | null, 
/**
 * Phase 81.19.b locale follow-up item 6 — resolved BCP-47
 * locale for this binding (`InboundBinding.language` over
 * `AgentConfig.language`). When present, the SDK's STT
 * inbound transform handler trims to ISO-639-1 and passes
 * it as a hint to whisper for accented audio. `None` lets
 * whisper auto-detect.
 */
language?: string | null, };

// ─── EscalationReason.ts ────────────────────────────────────

/**
 * Operator-facing escalation reason. Closed enum (no
 * `Other` slot — agents that can't classify use `Other`,
 * which is itself a value).
 */
export type EscalationReason = "out_of_scope" | "missing_data" | "needs_human_judgment" | "complaint" | "error" | "ambiguity" | "policy_violation" | "unknown_query" | "other";

// ─── EscalationUrgency.ts ────────────────────────────────────

/**
 * Operator-facing urgency hint. Default `Normal`.
 */
export type EscalationUrgency = "low" | "normal" | "high";

// ─── EventSourceMeta.ts ────────────────────────────────────

/**
 * Metadata describing the event that triggered an agent turn.
 *
 * Wire-shape struct — caller-built by the event-subscriber
 * runtime, caller-read by microapps and downstream tools.
 * Field additions are deliberate semver-major (the JSON wire
 * shape changes regardless), so this type is intentionally
 * **not** `#[non_exhaustive]`.
 */
export type EventSourceMeta = { 
/**
 * NATS subject that triggered the turn (e.g.
 * `"webhook.github_main.pull_request"`).
 */
subject: string, 
/**
 * Envelope id from the upstream event payload (when
 * available — webhook events carry one;
 * custom-published events may not).
 */
envelope_id: string | null, 
/**
 * Synthesis mode the binding was configured with —
 * `"synthesize"` or `"tick"`. Tools can branch behaviour
 * (e.g. fetch payload only when mode is `"tick"`).
 */
synthesis_mode: string, };

// ─── InboundKind.ts ────────────────────────────────────

/**
 * 3-way discriminator for the origin of an agent turn.
 *
 * Mirrors the trichotomy used by inbound provenance tracking
 * (external_user / inter_session / internal_system) so microapps
 * can branch handlers on the message origin without re-deriving
 * it from sender_id presence alone.
 */
export type InboundKind = "external_user" | "internal_system" | "inter_session";

// ─── InboundMessageMeta.ts ────────────────────────────────────

/**
 * Per-turn metadata about the inbound message that triggered the
 * agent turn.
 *
 * Stamped on every tool call dispatched to a Phase 11 stdio
 * extension or a Phase 12 MCP server (under
 * `params._meta.nexo.inbound`). All fields except `kind` are
 * optional; consumers must tolerate absence and branch
 * gracefully.
 *
 * # Example — external user message
 *
 * ```
 * use nexo_tool_meta::{InboundKind, InboundMessageMeta};
 *
 * let meta = InboundMessageMeta::external_user("+5491100", "wa.ABCD1234");
 * assert_eq!(meta.kind, InboundKind::ExternalUser);
 * assert_eq!(meta.sender_id.as_deref(), Some("+5491100"));
 * assert_eq!(meta.msg_id.as_deref(), Some("wa.ABCD1234"));
 * ```
 *
 * # Example — internal system tick
 *
 * ```
 * use nexo_tool_meta::{InboundKind, InboundMessageMeta};
 *
 * let meta = InboundMessageMeta::internal_system();
 * assert_eq!(meta.kind, InboundKind::InternalSystem);
 * assert!(meta.sender_id.is_none());
 * assert!(meta.msg_id.is_none());
 * ```
 */
export type InboundMessageMeta = { 
/**
 * Origin discriminator. Always present when the bucket is.
 */
kind: InboundKind, 
/**
 * Provider-native sender id (E.164 phone, telegram_user_id,
 * RFC822 from-address, slack U-id, …). `None` for kinds
 * other than `ExternalUser` and for paths where the provider
 * does not expose a sender id (e.g. webhook with no auth).
 */
sender_id?: string | null, 
/**
 * Provider-native message id (single canonical, no shortened
 * alias). Used for idempotency, dedupe, and as the
 * `reply_to_msg_id` target on subsequent turns. When a
 * debounce window collapses several inbound messages into a
 * single turn, this carries the id of the **first** message
 * in the batch.
 */
msg_id?: string | null, 
/**
 * Inbound timestamp in UTC. Wire shape: RFC3339 string via
 * chrono's serde adapter. Producers must clamp wildly-skewed
 * provider timestamps to `now()` before emitting.
 */
inbound_ts?: string | null, 
/**
 * Provider-native id of the message this one replies to.
 * `None` when the inbound is not a reply.
 */
reply_to_msg_id?: string | null, 
/**
 * `true` when the inbound carries non-text media
 * (image/audio/video/file/sticker). Microapps gate
 * media-aware tools on this; the actual bytes/URLs live in
 * `arguments`, not in `_meta`.
 */
has_media?: boolean, 
/**
 * Origin session id when `kind == InterSession` (delegation
 * receive). `None` otherwise.
 */
origin_session_id?: string | null, };

// ─── McpServerDetail.ts ────────────────────────────────────

/**
 * Full detail used by `mcp/get` + `mcp/upsert` payloads. Fields
 * not relevant to a given transport are `None` / empty.
 */
export type McpServerDetail = { 
/**
 * Stable identifier (key in `mcp.servers`).
 */
name: string, 
/**
 * Transport kind (`"stdio"` | `"streamable_http"` | `"sse"` | `"auto"`).
 */
transport: string, 
/**
 * Stdio transport — executable path / shell command.
 */
command?: string | null, 
/**
 * Stdio transport — argv tail.
 */
args?: Array<string>, 
/**
 * Stdio transport — env vars forwarded to the child.
 */
env?: { [key in string]: string }, 
/**
 * Stdio transport — working directory.
 */
cwd?: string | null, 
/**
 * HTTP / SSE / Auto transport — server URL.
 */
url?: string | null, 
/**
 * HTTP / SSE / Auto transport — extra headers.
 */
headers?: { [key in string]: string }, 
/**
 * All transports — log level override.
 */
log_level?: string | null, 
/**
 * All transports — per-server override of the global
 * `mcp.context.passthrough` flag.
 */
context_passthrough?: boolean | null, };

// ─── McpServerSummary.ts ────────────────────────────────────

/**
 * Compact summary used by `mcp/list` responses.
 */
export type McpServerSummary = { 
/**
 * Stable identifier (key in `mcp.servers`).
 */
name: string, 
/**
 * Transport kind (`"stdio"` | `"streamable_http"` | `"sse"` | `"auto"`).
 */
transport: string, 
/**
 * Optional log level override (passed to the server via
 * `logging/setLevel` post-init when supported).
 */
log_level?: string | null, };

// ─── McpServersDeleteParams.ts ────────────────────────────────────

/**
 * Params for `nexo/admin/mcp/delete`.
 */
export type McpServersDeleteParams = { 
/**
 * Server name to remove.
 */
name: string, };

// ─── McpServersDeleteResponse.ts ────────────────────────────────────

/**
 * Response for `nexo/admin/mcp/delete`.
 */
export type McpServersDeleteResponse = { 
/**
 * `true` when the entry was removed, `false` when the name
 * had no record (idempotent retry safe).
 */
removed: boolean, };

// ─── McpServersGetParams.ts ────────────────────────────────────

/**
 * Params for `nexo/admin/mcp/get`.
 */
export type McpServersGetParams = { 
/**
 * Server name to fetch.
 */
name: string, };

// ─── McpServersGetResponse.ts ────────────────────────────────────

/**
 * Response for `nexo/admin/mcp/get`. `server: None` is the
 * not-found case (daemon does NOT return an error so callers
 * can probe for existence cheaply).
 */
export type McpServersGetResponse = { 
/**
 * Matching server, or `None` when the name is unknown.
 */
server: McpServerDetail | null, };

// ─── McpServersListResponse.ts ────────────────────────────────────

/**
 * Response for `nexo/admin/mcp/list`.
 */
export type McpServersListResponse = { 
/**
 * Servers in stable alpha order by name.
 */
servers: Array<McpServerSummary>, };

// ─── McpServersUpsertResponse.ts ────────────────────────────────────

/**
 * Response for `nexo/admin/mcp/upsert`.
 */
export type McpServersUpsertResponse = { 
/**
 * Final server record after the write.
 */
server: McpServerDetail, 
/**
 * `true` when this call created a new server, `false` when
 * it updated an existing one (idempotent retry).
 */
created: boolean, };

// ─── MemoryEntryWire.ts ────────────────────────────────────

/**
 * One memory entry over the wire. Mirrors
 * `nexo_memory::MemoryEntry` minus internal-only fields.
 */
export type MemoryEntryWire = { 
/**
 * Stable UUID (string for wire stability).
 */
id: string, 
/**
 * Owning agent.
 */
agent_id: string, 
/**
 * Memory body (markdown / plain text).
 */
content: string, 
/**
 * Operator-set tags (`#user`, `#feedback`, etc.).
 */
tags: Array<string>, 
/**
 * Auto-derived concept tags (Phase 10.7 derivation).
 */
concept_tags: Array<string>, 
/**
 * ISO-8601 UTC timestamp of memory creation.
 */
created_at: string, 
/**
 * Memory type (User / Feedback / Project / Reference) —
 * drives per-type half-life decay in scoring.
 */
memory_type?: string | null, };

// ─── MemoryQueryParams.ts ────────────────────────────────────

/**
 * Params for `nexo/admin/memory/query`.
 */
export type MemoryQueryParams = { 
/**
 * Agent whose memory to search.
 */
agent_id: string, 
/**
 * Free-text query. Empty string returns the most recent
 * entries (recency wins when no query terms hit the FTS5
 * MATCH).
 */
query: string, 
/**
 * Max rows to return. Server-side clamp [1, 100], default 20.
 */
limit: number, };

// ─── MemoryQueryResponse.ts ────────────────────────────────────

/**
 * Response for `nexo/admin/memory/query`.
 */
export type MemoryQueryResponse = { 
/**
 * Matching entries newest-first within the relevance band.
 */
entries: Array<MemoryEntryWire>, };

// ─── MemorySnapshotsDeleteParams.ts ────────────────────────────────────

/**
 * Params for `nexo/admin/memory/delete_snapshot`.
 */
export type MemorySnapshotsDeleteParams = { 
/**
 * Owning agent. Snapshots are partitioned by agent_id, so a
 * rogue id can't delete another agent's bundle.
 */
agent_id: string, 
/**
 * Tenant scope. Empty string = "default".
 */
tenant: string, 
/**
 * Snapshot id (UUID-shaped) to remove.
 */
id: string, };

// ─── MemorySnapshotsDeleteResponse.ts ────────────────────────────────────

/**
 * Response for `nexo/admin/memory/delete_snapshot`.
 */
export type MemorySnapshotsDeleteResponse = { 
/**
 * `true` when the bundle was removed; idempotent retry safe
 * (returns `true` on missing id too — daemon's local-fs
 * delete is `Ok(())` for already-gone bundles).
 */
removed: boolean, };

// ─── MemorySnapshotsListParams.ts ────────────────────────────────────

/**
 * Params for `nexo/admin/memory/list_snapshots`.
 */
export type MemorySnapshotsListParams = { 
/**
 * Agent whose snapshots to list.
 */
agent_id: string, 
/**
 * Tenant scope. Empty string = "default".
 */
tenant: string, };

// ─── MemorySnapshotsListResponse.ts ────────────────────────────────────

/**
 * Response for `nexo/admin/memory/list_snapshots`.
 */
export type MemorySnapshotsListResponse = { 
/**
 * Snapshots ordered by `created_at_ms` descending (newest first).
 */
snapshots: Array<SnapshotMetaWire>, };

// ─── MicroappError.ts ────────────────────────────────────

/**
 * Notification payload.
 */
export type MicroappError = { 
/**
 * Operator-facing extension id (`extensions.yaml.entries.<id>`).
 */
microapp_id: string, 
/**
 * Discriminator for the four canonical error categories.
 */
kind: MicroappErrorKind, 
/**
 * JSON-RPC `id` that triggered the error, when applicable.
 * `None` for `Exit` (no in-flight call) and for boot-time
 * failures.
 */
correlation_id?: string | null, 
/**
 * UTC wall-clock at which the daemon observed the error.
 */
occurred_at: string, 
/**
 * One-line human-readable summary surfaced in the admin-ui
 * hover tooltip and Prometheus annotations. Keep terse —
 * stack trace goes in `stack_trace`.
 */
summary: string, 
/**
 * Optional multi-line stack trace / traceback. Bounded by
 * the daemon's stdio reader (16 KiB cap by convention) so
 * a runaway microapp can't blow up the broker.
 */
stack_trace?: string | null, };

// ─── MicroappErrorKind.ts ────────────────────────────────────

/**
 * Kind discriminator. `#[non_exhaustive]` so future kinds
 * (e.g. `RateLimitTripped` once 83.16's respawn-throttle
 * follow-up ships) can land non-major.
 */
export type MicroappErrorKind = "init_timeout" | "handler_panic" | "exit" | "capability_denied";

// ─── OutboundReplyContext.ts ────────────────────────────────────

/**
 * Context the framework hands transformers + channel plugins for
 * every outbound reply. Read-only.
 */
export type OutboundReplyContext = { 
/**
 * Stable agent id producing the reply.
 */
agent_id: string, 
/**
 * Session UUID stringified.
 */
session_id: string, 
/**
 * `whatsapp` / `telegram` / `email` / etc.
 */
channel: string, 
/**
 * Plugin instance discriminator (e.g. `smoketest`,
 * `sucursal-norte`). `None` for single-instance channels.
 */
instance?: string | null, 
/**
 * Channel-native recipient address (whatsapp jid, telegram
 * chat_id, …). Optional because some pipelines (e.g. system-
 * injected ticks) don't have one yet.
 */
recipient?: string | null, 
/**
 * Tenant id when the agent is tenant-scoped, otherwise `None`.
 */
tenant_id?: string | null, 
/**
 * Conversation key used by operator UIs to group messages —
 * matches the one the firehose store + chat sidebar use
 * (`<agent_id>:session:<session_id>` for transcript-keyed
 * chats). Microapps key per-conversation state on this.
 */
conversation_key: string, 
/**
 * ISO-639-1 hint from `agents.yaml.<id>.language`. Lets reply
 * transformers localise their behaviour (e.g. voice_mode
 * picks a region-appropriate Edge voice when the operator
 * hasn't manually overridden it).
 */
language?: string | null, };

// ─── PluginsDoctorResponse.ts ────────────────────────────────────

/**
 * Response for `nexo/admin/plugins/doctor`.
 */
export type PluginsDoctorResponse = { 
/**
 * Full `PluginDiscoveryReport` JSON. Identical to what the
 * `agent doctor plugins --json` CLI emits — a stable wire
 * shape since Phase 81.11 (`doctor_render::render_json`).
 */
report: JsonValue, 
/**
 * Server-side wall-clock when the report was built (ms
 * since epoch). Operators see this as a "as of …" hint.
 */
generated_at_ms: number, };

// ─── ProcessingControlState.ts ────────────────────────────────────

/**
 * Persisted control state for one scope. `AgentActive` is the
 * default — every scope starts in this state and the store
 * only allocates a row once an operator pauses it.
 */
export type ProcessingControlState = { "state": "agent_active" } | { "state": "paused_by_operator", 
/**
 * Echo of the scope so callers reading state alone
 * have the discriminator handy.
 */
scope: ProcessingScope, 
/**
 * Epoch ms when the pause was set.
 */
paused_at_ms: number, 
/**
 * `token_hash` of the operator's bearer (Phase 82.12
 * helper) so audits can correlate without storing the
 * cleartext token.
 */
operator_token_hash: string, 
/**
 * Free-form reason. Optional.
 */
reason?: string | null, };

// ─── ProcessingScope.ts ────────────────────────────────────

/**
 * Scope the operator is suspending (or operating on).
 * `#[non_exhaustive]` so adding new agent shapes later is
 * non-breaking. v0 only routes `Conversation` end-to-end;
 * other variants are accepted on the wire but the dispatcher
 * returns `-32601 not_implemented`.
 */
export type ProcessingScope = { "kind": "conversation", 
/**
 * Owning agent.
 */
agent_id: string, 
/**
 * Channel plugin (e.g. `whatsapp`).
 */
channel: string, 
/**
 * Channel-side account id (e.g. WA business id).
 */
account_id: string, 
/**
 * Counterparty id (e.g. WA jid).
 */
contact_id: string, 
/**
 * Phase 80.9 — populated when the conversation
 * arrived via an MCP channel server (e.g. `slack`).
 * `None` for native-channel inbounds.
 */
mcp_channel_source?: string | null, } | { "kind": "agent_binding", 
/**
 * Owning agent.
 */
agent_id: string, 
/**
 * Channel plugin.
 */
channel: string, 
/**
 * Channel-side account id.
 */
account_id: string, } | { "kind": "agent", 
/**
 * Agent id.
 */
agent_id: string, } | { "kind": "event_stream", 
/**
 * Owning agent.
 */
agent_id: string, 
/**
 * Subject glob.
 */
subject_pattern: string, } | { "kind": "batch_queue", 
/**
 * Owning agent.
 */
agent_id: string, 
/**
 * Queue name.
 */
queue_name: string, } | { "kind": "custom", 
/**
 * Owning agent.
 */
agent_id: string, 
/**
 * Caller-defined scope discriminator.
 */
scope_kind: string, 
/**
 * Caller-defined scope id.
 */
scope_id: string, };

// ─── ResolvedBy.ts ────────────────────────────────────

/**
 * How a previously-pending escalation was settled.
 */
export type ResolvedBy = { "kind": "operator_takeover" } | { "kind": "operator_dismissed", 
/**
 * Free-form reason — kept for the audit log.
 */
reason: string, } | { "kind": "agent_resolved" };

// ─── SecurityEventKind.ts ────────────────────────────────────

/**
 * Phase 82.10.o — security-domain audit events. Nested under
 * [`AgentEventKind::SecurityEvent`] so subscribers persist
 * every variant alongside transcript / escalation events for
 * a unified audit log.
 */
export type SecurityEventKind = { "security_kind": "token_rotated", 
/**
 * Epoch milliseconds when the rotation persisted.
 */
at_ms: number, 
/**
 * Previous operator-token-hash (16-char sha256-hex
 * prefix). Zeroed (`""`) for the very first rotation
 * after boot when no prior hash is in cache.
 */
prev_hash: string, 
/**
 * New operator-token-hash.
 */
new_hash: string, 
/**
 * Optional operator-supplied audit hint, capped to
 * `auth::REASON_MAX_LEN` chars by the handler.
 */
reason?: string | null, };

// ─── SnapshotMetaWire.ts ────────────────────────────────────

/**
 * Wire-side projection of `nexo_memory_snapshot::SnapshotMeta`.
 * Internal fields (bundle_path, schema_versions, git_oid)
 * surfaced as opaque strings for forward-compat.
 */
export type SnapshotMetaWire = { 
/**
 * Snapshot id (UUID-shaped string).
 */
id: string, 
/**
 * Owning agent.
 */
agent_id: string, 
/**
 * Tenant scope.
 */
tenant: string, 
/**
 * Optional human-readable label set at create time.
 */
label?: string | null, 
/**
 * Wall-clock millis since epoch when the bundle was written.
 */
created_at_ms: number, 
/**
 * Absolute filesystem path of the bundle archive.
 */
bundle_path: string, 
/**
 * Bundle size in bytes (after compression / encryption).
 */
bundle_size_bytes: number, 
/**
 * Hex-encoded SHA-256 of the bundle.
 */
bundle_sha256: string, 
/**
 * `Some(oid)` when git-mode snapshots captured a commit.
 */
git_oid?: string | null, 
/**
 * True when the bundle is age-encrypted (`*.tar.zst.age`).
 */
encrypted: boolean, 
/**
 * True when redaction policies stripped fields at capture time.
 */
redactions_applied: boolean, };

// ─── TranscriptRole.ts ────────────────────────────────────

/**
 * Speaker role mirror — kept on the wire side so SDK types
 * don't pull in the core crate. Matches
 * `nexo_core::agent::transcripts::TranscriptRole`.
 */
export type TranscriptRole = "user" | "assistant" | "tool" | "system";

// ─── WebhookEnvelope.ts ────────────────────────────────────

/**
 * Typed JSON envelope nexo publishes after every accepted
 * webhook request.
 *
 * Subscribers correlate events via `envelope_id` (deterministic
 * dedup) and `received_at_ms` (late-binding analytics).
 * `headers_subset` is a defensive allowlist — secrets like
 * `Authorization` / `Cookie` / signature headers are stripped
 * before publish, so a NATS subscriber sees only non-secret
 * correlation IDs.
 *
 * Unlike [`crate::BindingContext`], this struct is intentionally
 * *not* `#[non_exhaustive]`: it represents a wire-shape value
 * constructed on both sides (the daemon writes it; tests +
 * mocks build it via struct-literal). Field additions are
 * semver-major because the JSON wire shape changes regardless.
 *
 * # Example
 *
 * Microapps typically deserialise the envelope from a NATS
 * payload:
 *
 * ```
 * use nexo_tool_meta::WebhookEnvelope;
 *
 * let payload = serde_json::json!({
 *     "schema": 1,
 *     "source_id": "github_main",
 *     "event_kind": "pull_request",
 *     "body_json": {"action": "opened"},
 *     "headers_subset": {},
 *     "received_at_ms": 0,
 *     "envelope_id": "00000000-0000-0000-0000-000000000000",
 *     "client_ip": null
 * });
 * let env: WebhookEnvelope = serde_json::from_value(payload).unwrap();
 * assert_eq!(env.schema, 1);
 * assert_eq!(env.source_id, "github_main");
 * ```
 */
export type WebhookEnvelope = { 
/**
 * Wire-shape version. Always [`ENVELOPE_SCHEMA_VERSION`].
 */
schema: number, 
/**
 * Operator-assigned source identifier — matches the
 * `webhook_receiver.sources[].id` YAML field.
 */
source_id: string, 
/**
 * Event kind extracted from the inbound request (header or
 * JSON body path, per source config).
 */
event_kind: string, 
/**
 * Inbound body, parsed as JSON. Non-JSON bodies are wrapped
 * as `{ "raw_base64": "..." }` upstream.
 */
body_json: JsonValue, 
/**
 * Allowlisted headers forwarded for downstream correlation.
 * Authorization / Cookie / signature headers are stripped.
 */
headers_subset: { [key in string]: string }, 
/**
 * Server-side receipt timestamp in milliseconds since epoch.
 */
received_at_ms: number, 
/**
 * Random per-envelope identifier — useful for dedup.
 */
envelope_id: string, 
/**
 * Resolved client IP (after trusted-proxy logic). `None`
 * for envelopes built outside an HTTP request context.
 */
client_ip: string | null, };
