// AUTOGENERATED — do not edit by hand.
//
// Generated from `nexo-tool-meta` `#[ts(export)]` structs by
// `proyecto/scripts/regen-ts-types.sh`. The CI lint
// `proyecto/scripts/lint-ts-types-sync.sh` ensures this file
// matches the current Rust sources at HEAD; if it doesn't,
// regenerate via:
//
//   cd proyecto && bash scripts/regen-ts-types.sh
//
// Source of truth: `proyecto/crates/tool-meta/src/`.

/**
 * Recursive JSON value type — mirrors `serde_json::Value` on the
 * Rust side. ts-rs would normally emit a separate file for this;
 * we inline it here so the single-file `types.gen.ts` is
 * self-contained.
 */
export type JsonValue =
  | null
  | boolean
  | number
  | string
  | JsonValue[]
  | { [key: string]: JsonValue };

// ─── AdminAuditResult.ts ────────────────────────────────────

/**
 * Outcome of an admin RPC dispatch — written to the audit table
 * alongside every call.
 */
export type AdminAuditResult = "ok" | "error" | "denied";

// ─── AdminAuditRow.ts ────────────────────────────────────

/**
 * One row of `microapp_admin_audit`. Stable wire shape — every
 * field is present in the JSON payload returned by
 * `nexo/admin/microapp_audit/tail`.
 */
export type AdminAuditRow = { 
/**
 * Microapp identity (extension id from `extensions.yaml`).
 */
microapp_id: string, 
/**
 * Full JSON-RPC method (`nexo/admin/<domain>/<method>`).
 */
method: string, 
/**
 * Required capability (e.g. `agents_crud`). When the call
 * was denied, this is the capability that was missing.
 */
capability: string, 
/**
 * SHA-256 of canonicalised params (sorted keys). Lets
 * operators detect repeated identical calls without storing
 * PII payloads.
 */
args_hash: string, 
/**
 * Epoch milliseconds when dispatch started.
 */
started_at_ms: number, 
/**
 * `"ok"` | `"error"` | `"denied"`.
 */
result: AdminAuditResult, 
/**
 * Wall-clock duration of the dispatch.
 */
duration_ms: number, 
/**
 * Tenant scope for the call. Sniffed from
 * `params.tenant_id` (string) when present; legacy rows /
 * non-tenant-scoped calls (echo, pairing, credentials)
 * leave it `null`.
 */
tenant_id?: string | null, };

// ─── AgentEventKind.ts ────────────────────────────────────

/**
 * Discriminated event variant. v0 only emits
 * `TranscriptAppended`. Other slots are reserved enum entries
 * surfaced when the corresponding agent kind ships.
 */
export type AgentEventKind = { "kind": "transcript_appended", 
/**
 * Owning agent.
 */
agent_id: string, 
/**
 * Conversation scope.
 */
session_id: string, 
/**
 * Monotonic sequence within `session_id` — equal to the
 * 0-based index of the entry in the session's JSONL.
 */
seq: number, 
/**
 * Speaker role.
 */
role: TranscriptRole, 
/**
 * Redacted body (PII replaced with `[REDACTED:label]`).
 */
body: string, 
/**
 * Epoch milliseconds when the entry was recorded.
 */
sent_at_ms: number, 
/**
 * Opaque external sender id when applicable (channel
 * user id, peer agent id, …).
 */
sender_id?: string | null, 
/**
 * Channel/plugin that produced or received the entry
 * (e.g. `whatsapp`, `telegram`, `internal`).
 */
source_plugin: string, 
/**
 * Owning tenant. `None` for agents
 * predating multi-tenant. Firehose subscribers filter
 * on this without re-querying agents.yaml.
 */
tenant_id?: string | null, } | { "kind": "pending_inbounds_dropped", 
/**
 * Owning agent.
 */
agent_id: string, 
/**
 * Scope under which the drop happened. Carried whole
 * (rather than just `(channel, account_id, contact_id)`)
 * so future scope variants stay forward-compatible.
 */
scope: ProcessingScope, 
/**
 * Number of pending inbounds evicted by THIS push.
 */
dropped: number, 
/**
 * Epoch ms when the eviction happened.
 */
at_ms: number, } | { "kind": "escalation_requested", 
/**
 * Owning agent.
 */
agent_id: string, 
/**
 * Scope of the work item the agent is escalating.
 */
scope: ProcessingScope, 
/**
 * Free-form summary the agent supplied (already capped
 * to 500 chars by the admin handler before emit).
 */
summary: string, 
/**
 * Closed-enum reason for the escalation.
 */
reason: EscalationReason, 
/**
 * Operator hint on how aggressively to surface.
 */
urgency: EscalationUrgency, 
/**
 * Epoch ms when the agent raised the request.
 */
requested_at_ms: number, 
/**
 * Owning tenant; `None` for legacy /
 * single-tenant deployments. Firehose subscribers route
 * per-tenant without re-querying `agents.yaml`.
 */
tenant_id?: string | null, } | { "kind": "escalation_resolved", 
/**
 * Owning agent.
 */
agent_id: string, 
/**
 * Scope that was settled. Same value the `Pending`
 * emit carried.
 */
scope: ProcessingScope, 
/**
 * Epoch ms when the resolution happened.
 */
resolved_at_ms: number, 
/**
 * How the escalation was settled.
 */
by: ResolvedBy, 
/**
 * Owning tenant. Mirrors the
 * `Requested` shape so the pair stays
 * shape-symmetrical.
 */
tenant_id?: string | null, } | { "kind": "processing_state_changed", 
/**
 * Owning agent (denormalised from `scope` so subscribers
 * filter without parsing the discriminator).
 */
agent_id: string, 
/**
 * Scope whose state flipped.
 */
scope: ProcessingScope, 
/**
 * State observed immediately before the transition.
 */
prev_state: ProcessingControlState, 
/**
 * State the handler installed.
 */
new_state: ProcessingControlState, 
/**
 * Epoch ms when the transition happened.
 */
at_ms: number, 
/**
 * Owning tenant. `None` for legacy /
 * single-tenant deployments.
 */
tenant_id?: string | null, } | { "kind": "security_event", } & ({ "security_kind": "token_rotated", 
/**
 * Epoch milliseconds when the rotation persisted.
 */
at_ms: number, 
/**
 * Previous operator-token-hash (16-char sha256-hex
 * prefix). Zeroed (`""`) for the very first rotation
 * after boot when no prior hash is in cache.
 */
prev_hash: string, 
/**
 * New operator-token-hash.
 */
new_hash: string, 
/**
 * Optional operator-supplied audit hint, capped to
 * `auth::REASON_MAX_LEN` chars by the handler.
 */
reason?: string | null, }) | { "kind": "peer_typing", 
/**
 * Channel that produced the presence signal
 * (e.g. `whatsapp`).
 */
channel: string, 
/**
 * Channel-instance qualifier (e.g. `smoketest`). Empty
 * when the channel does not support multi-instance.
 */
account_id: string, 
/**
 * Channel-native sender id (e.g.
 * `573154645370@s.whatsapp.net`).
 */
sender_id: string, 
/**
 * `true` = peer is currently typing (composing).
 * `false` = peer stopped typing (paused).
 */
composing: boolean, 
/**
 * Epoch ms when the plugin observed the presence change.
 */
at_ms: number, 
/**
 * Owning agent when the plugin can resolve which agent
 * the conversation belongs to (single-agent inbound
 * binding). `None` for multi-agent setups — operator
 * dashboards then match by `(channel, account_id,
 * sender_id)` against every conversation.
 */
agent_id?: string | null, 
/**
 * Owning tenant. `None` for legacy /
 * single-tenant deployments.
 */
tenant_id?: string | null, } | { "kind": "whatsapp_bot_message", 
/**
 * WhatsApp plugin instance label (`smoketest`,
 * `default`, …). Resolves to the paired account.
 */
instance: string, 
/**
 * Bot JID, e.g. `718584497008509@bot`.
 */
bot_jid: string, 
/**
 * This chunk's stanza id (different per chunk).
 */
msg_id: string, 
/**
 * The original outbound id we sent to the bot. Constant
 * across every chunk of one logical reply.
 */
target_id: string, 
/**
 * `first` / `inner` / `last`. `last` = reply complete.
 */
edit: string, 
/**
 * Concatenated `AIRichResponseMessage.submessages[].messageText`
 * for this snapshot.
 */
text: string, 
/**
 * Epoch ms when the daemon received the chunk.
 */
at_ms: number, };

// ─── AuditTailFilter.ts ────────────────────────────────────

/**
 * Filter passed to `nexo/admin/microapp_audit/tail`. Every
 * field optional; combine to narrow the result set.
 */
export type AuditTailFilter = { 
/**
 * Restrict to a single microapp.
 */
microapp_id?: string | null, 
/**
 * Restrict to one JSON-RPC method.
 */
method?: string | null, 
/**
 * Restrict to one outcome.
 */
result?: AdminAuditResult | null, 
/**
 * Restrict to one tenant.
 */
tenant_id?: string | null, 
/**
 * Lower-bound timestamp (epoch ms). Use
 * `now - duration_ms` for human-friendly windows
 * ("last 24h", "last 7d", …).
 */
since_ms?: number | null, 
/**
 * Max rows to return. Server clamps to `[1, 500]`. `0` →
 * default 50.
 */
limit: number, 
/**
 * Pagination offset. `0` for the first page; subsequent
 * pages set this to the previous response's `next_offset`.
 */
offset: number, };

// ─── AuditTailPage.ts ────────────────────────────────────

/**
 * Paginated response for `nexo/admin/microapp_audit/tail`.
 * Frontend stores `entries`, appends on `loadMore` until
 * `has_more = false`.
 */
export type AuditTailPage = { 
/**
 * Rows in newest-first order, capped by `filter.limit`.
 */
entries: Array<AdminAuditRow>, 
/**
 * Total matching rows (without `limit`/`offset`). Useful
 * for "showing N of M" UI labels.
 */
total: number, 
/**
 * `true` when `entries.len()` was capped by `limit` and
 * more rows match the filter.
 */
has_more: boolean, 
/**
 * Offset to pass to the next call's `filter.offset`.
 * `None` when `has_more = false`.
 */
next_offset?: number | null, };

// ─── BindingContext.ts ────────────────────────────────────

/**
 * Identifies which inbound binding a tool call originated from.
 *
 * Stamped on every tool call dispatched to a stdio extension or
 * an MCP server (under `params._meta.nexo.binding`).
 * A microapp reads it to route work to the correct tenant /
 * channel / account.
 *
 * `binding_id` is rendered as `<channel>:<account_id|"default">`
 * — a stable identifier that survives `agents.yaml` reloads
 * (does NOT depend on the binding vector index).
 *
 * `mcp_channel_source` is populated when the inbound that
 * triggered the call arrived via an MCP channel
 * server (`"slack"`, `"telegram"`, etc.), allowing a tool to
 * distinguish "telegram-binding answered via MCP slack server"
 * from "telegram-binding answered via the native Telegram
 * plugin" while still seeing the same `(channel, account_id)`
 * tuple.
 *
 * # Example
 *
 * ```
 * use nexo_tool_meta::BindingContext;
 *
 * let ctx = BindingContext::agent_only("ana");
 * assert_eq!(ctx.agent_id, "ana");
 * assert!(ctx.channel.is_none());
 * ```
 */
export type BindingContext = { 
/**
 * Stable agent identifier (`agents.yaml.<id>`).
 */
agent_id: string, 
/**
 * Active session UUID. `None` outside an LLM turn (heartbeat
 * bootstrap, delegation receive, tests).
 */
session_id: string | null, 
/**
 * Channel name as declared in `InboundBinding.plugin`
 * (`"whatsapp"`, `"telegram"`, `"email"`, `"web"`, …).
 * `None` for contexts without a binding match.
 */
channel: string | null, 
/**
 * Account / instance discriminator from
 * `InboundBinding.instance`. `None` when the binding
 * declared no instance (single-account default).
 */
account_id: string | null, 
/**
 * Stable binding identifier rendered as
 * `<channel>:<account_id|"default">`. `None` for
 * bindingless contexts.
 */
binding_id: string | null, 
/**
 * MCP channel server name when the inbound
 * arrived via `notifications/nexo/channel`. `None` for
 * native-channel inbounds. Examples: `"slack"`,
 * `"telegram"`, `"imessage"`.
 */
mcp_channel_source: string | null, 
/**
 * Event-subscriber metadata when the agent's
 * inbound was synthesised from a NATS event (subject pattern
 * match). `None` for human-message turns / native-channel
 * inbounds.
 */
event_source: EventSourceMeta | null, 
/**
 * SaaS tenant key. `None` for
 * agents that predate the multi-tenant model
 * (`agents.yaml.<id>` without an `tenant_id` field).
 * Multi-tenant filtering across admin RPC + microapp tools
 * keys on this field. Sits ABOVE `account_id`, which
 * remains the channel-side discriminator.
 */
tenant_id?: string | null, 
/**
 * Resolved BCP-47
 * locale for this binding (`InboundBinding.language` over
 * `AgentConfig.language`). When present, the SDK's STT
 * inbound transform handler trims to ISO-639-1 and passes
 * it as a hint to whisper for accented audio. `None` lets
 * whisper auto-detect.
 */
language?: string | null, };

// ─── CompatStatus.ts ────────────────────────────────────

/**
 * SDK semver compat result. Drives the install button's enabled
 * state on the UI card.
 */
export type CompatStatus = { "kind": "compatible" } | { "kind": "needs_upgrade", 
/**
 * `semver::VersionReq` display of the required range.
 */
required: string, 
/**
 * `semver::Version` display of the running daemon's SDK.
 */
current: string, } | { "kind": "incompatible", 
/**
 * Human-readable explanation surfaced as the badge tooltip
 * (e.g. "Plugin pins nexo-sdk = 0.0.x; daemon ships 0.1+").
 */
reason: string, } | { "kind": "unknown" };

// ─── DiscoveredPlugin.ts ────────────────────────────────────

/**
 * Single catalogue entry. Merged from one or more sources; UI
 * renders this as a card.
 */
export type DiscoveredPlugin = { 
/**
 * Canonical crate name (`nexo-plugin-telegram`). Unique key
 * across sources — merge-by-name dedups duplicates.
 */
name: string, 
/**
 * Latest non-yanked semver. `None` when the source doesn't
 * publish version info (rare; GitHub-topic-only entries
 * without crates.io publication).
 */
version?: string | null, 
/**
 * One-line summary. Pulled from crates.io description /
 * repo description / curated index entry.
 */
description?: string | null, 
/**
 * GitHub org or crates.io owner login. Drives the
 * `trust_tier` derivation against `TrustedKeysConfig.authors`.
 */
owner: string, 
/**
 * Where the daemon found this entry. Multiple sources merge
 * into one entry with the union of sources here — operators
 * see "available on crates.io + indexed" badges.
 */
sources: Array<PluginSource>, 
/**
 * Canonical repo URL (`https://github.com/org/name`). Used as
 * the fallback `repo` slug when constructing `install_params`
 * for the Release path.
 */
repo_url?: string | null, 
/**
 * Plugin homepage / docs URL. Optional; surfaced as a "Learn
 * more" link on the UI card.
 */
homepage?: string | null, 
/**
 * Free-form tags from crates.io keywords + curated index
 * metadata. Drives the search-by-tag filter.
 */
tags: Array<string>, 
/**
 * Functional category derived from `nexo-plugin.toml` manifest
 * sections at fetch time. Lets the UI bucket plugins by what
 * they do (channel / poller / tool / webhook / persona).
 */
category: PluginCategory, 
/**
 * Trust tier resolved against the daemon's `TrustedKeysConfig`
 * authors allowlist + curated index membership. Shipped as a
 * badge on the UI card; never enforced here — installation
 * still routes through Phase 97.1's signature pipeline.
 */
trust_tier: TrustTier, 
/**
 * Result of comparing the manifest's `[plugin.requires]
 * nexo-sdk = ">=…"` range against the running daemon's
 * `nexo_microapp_sdk::VERSION`. `Unknown` when no manifest
 * was fetched (404 / parse error / source-only entry).
 */
compat: CompatStatus, 
/**
 * Raw URL to the plugin's `nexo-plugin.toml` (or fallback
 * paths). Empty when the source doesn't expose one; UI hides
 * the "manifest" link when absent.
 */
manifest_url?: string | null, 
/**
 * Human-readable install command (`cargo install
 * nexo-plugin-X --version 0.3.0`). Convenient for the
 * copy-button on the UI card; the actual install is driven
 * by `install_params` below.
 */
install_cmd: string, 
/**
 * Pre-filled params for `nexo/admin/plugins/install`. A click
 * on the UI "Install" button opens the existing
 * [`crate::admin::plugin_install::PluginsInstallParams`]
 * modal with these values populated — operator can tweak
 * trust flags / source before submitting.
 */
install_params: PluginsInstallParams, };

// ─── EscalationReason.ts ────────────────────────────────────

/**
 * Operator-facing escalation reason. Closed enum (no
 * `Other` slot — agents that can't classify use `Other`,
 * which is itself a value).
 */
export type EscalationReason = "out_of_scope" | "missing_data" | "needs_human_judgment" | "complaint" | "error" | "ambiguity" | "policy_violation" | "unknown_query" | "other";

// ─── EscalationUrgency.ts ────────────────────────────────────

/**
 * Operator-facing urgency hint. Default `Normal`.
 */
export type EscalationUrgency = "low" | "normal" | "high";

// ─── EventSourceMeta.ts ────────────────────────────────────

/**
 * Metadata describing the event that triggered an agent turn.
 *
 * Wire-shape struct — caller-built by the event-subscriber
 * runtime, caller-read by microapps and downstream tools.
 * Field additions are deliberate semver-major (the JSON wire
 * shape changes regardless), so this type is intentionally
 * **not** `#[non_exhaustive]`.
 */
export type EventSourceMeta = { 
/**
 * NATS subject that triggered the turn (e.g.
 * `"webhook.github_main.pull_request"`).
 */
subject: string, 
/**
 * Envelope id from the upstream event payload (when
 * available — webhook events carry one;
 * custom-published events may not).
 */
envelope_id: string | null, 
/**
 * Synthesis mode the binding was configured with —
 * `"synthesize"` or `"tick"`. Tools can branch behaviour
 * (e.g. fetch payload only when mode is `"tick"`).
 */
synthesis_mode: string, };

// ─── InboundKind.ts ────────────────────────────────────

/**
 * 3-way discriminator for the origin of an agent turn.
 *
 * Mirrors the trichotomy used by inbound provenance tracking
 * (external_user / inter_session / internal_system) so microapps
 * can branch handlers on the message origin without re-deriving
 * it from sender_id presence alone.
 */
export type InboundKind = "external_user" | "internal_system" | "inter_session";

// ─── InboundMessageMeta.ts ────────────────────────────────────

/**
 * Per-turn metadata about the inbound message that triggered the
 * agent turn.
 *
 * Stamped on every tool call dispatched to a stdio
 * extension or an MCP server (under
 * `params._meta.nexo.inbound`). All fields except `kind` are
 * optional; consumers must tolerate absence and branch
 * gracefully.
 *
 * # Example — external user message
 *
 * ```
 * use nexo_tool_meta::{InboundKind, InboundMessageMeta};
 *
 * let meta = InboundMessageMeta::external_user("+5491100", "wa.ABCD1234");
 * assert_eq!(meta.kind, InboundKind::ExternalUser);
 * assert_eq!(meta.sender_id.as_deref(), Some("+5491100"));
 * assert_eq!(meta.msg_id.as_deref(), Some("wa.ABCD1234"));
 * ```
 *
 * # Example — internal system tick
 *
 * ```
 * use nexo_tool_meta::{InboundKind, InboundMessageMeta};
 *
 * let meta = InboundMessageMeta::internal_system();
 * assert_eq!(meta.kind, InboundKind::InternalSystem);
 * assert!(meta.sender_id.is_none());
 * assert!(meta.msg_id.is_none());
 * ```
 */
export type InboundMessageMeta = { 
/**
 * Origin discriminator. Always present when the bucket is.
 */
kind: InboundKind, 
/**
 * Provider-native sender id (E.164 phone, telegram_user_id,
 * RFC822 from-address, slack U-id, …). `None` for kinds
 * other than `ExternalUser` and for paths where the provider
 * does not expose a sender id (e.g. webhook with no auth).
 */
sender_id?: string | null, 
/**
 * Provider-native message id (single canonical, no shortened
 * alias). Used for idempotency, dedupe, and as the
 * `reply_to_msg_id` target on subsequent turns. When a
 * debounce window collapses several inbound messages into a
 * single turn, this carries the id of the **first** message
 * in the batch.
 */
msg_id?: string | null, 
/**
 * Inbound timestamp in UTC. Wire shape: RFC3339 string via
 * chrono's serde adapter. Producers must clamp wildly-skewed
 * provider timestamps to `now()` before emitting.
 */
inbound_ts?: string | null, 
/**
 * Provider-native id of the message this one replies to.
 * `None` when the inbound is not a reply.
 */
reply_to_msg_id?: string | null, 
/**
 * `true` when the inbound carries non-text media
 * (image/audio/video/file/sticker). Microapps gate
 * media-aware tools on this; the actual bytes/URLs live in
 * `arguments`, not in `_meta`.
 */
has_media?: boolean, 
/**
 * Origin session id when `kind == InterSession` (delegation
 * receive). `None` otherwise.
 */
origin_session_id?: string | null, };

// ─── InstallSource.ts ────────────────────────────────────

/**
 * Which delivery channel the daemon should use to fetch the
 * plugin binary. Defaults to [`InstallSource::Release`] — fastest
 * path for SaaS clients without a Rust toolchain.
 */
export type InstallSource = "release" | "cargo";

// ─── ManifestSummary.ts ────────────────────────────────────

/**
 * Subset of `nexo-plugin.toml` surfaced via
 * `nexo/admin/plugins/compat_check`. Lets the UI render a
 * pre-install dialog with manifest details without exposing the
 * full TOML.
 */
export type ManifestSummary = { 
/**
 * Manifest's `[plugin] id` field — canonical plugin identifier.
 */
plugin_id: string, 
/**
 * Manifest's `[plugin] version` field — declared semver.
 */
plugin_version: string, 
/**
 * `manifest_version` schema discriminator (currently `2`).
 */
manifest_version: number, 
/**
 * Raw `[plugin.requires] nexo-sdk` value (semver range string),
 * `None` when not declared.
 */
sdk_requires?: string | null, 
/**
 * Functional category derived from which manifest sections are
 * present (same logic that powers `DiscoveredPlugin.category`).
 */
category: PluginCategory, };

// ─── McpServerDetail.ts ────────────────────────────────────

/**
 * Full detail used by `mcp/get` + `mcp/upsert` payloads. Fields
 * not relevant to a given transport are `None` / empty.
 */
export type McpServerDetail = { 
/**
 * Stable identifier (key in `mcp.servers`).
 */
name: string, 
/**
 * Transport kind (`"stdio"` | `"streamable_http"` | `"sse"` | `"auto"`).
 */
transport: string, 
/**
 * Stdio transport — executable path / shell command.
 */
command?: string | null, 
/**
 * Stdio transport — argv tail.
 */
args?: Array<string>, 
/**
 * Stdio transport — env vars forwarded to the child.
 */
env?: { [key in string]: string }, 
/**
 * Stdio transport — working directory.
 */
cwd?: string | null, 
/**
 * HTTP / SSE / Auto transport — server URL.
 */
url?: string | null, 
/**
 * HTTP / SSE / Auto transport — extra headers.
 */
headers?: { [key in string]: string }, 
/**
 * All transports — log level override.
 */
log_level?: string | null, 
/**
 * All transports — per-server override of the global
 * `mcp.context.passthrough` flag.
 */
context_passthrough?: boolean | null, };

// ─── McpServerSummary.ts ────────────────────────────────────

/**
 * Compact summary used by `mcp/list` responses.
 */
export type McpServerSummary = { 
/**
 * Stable identifier (key in `mcp.servers`).
 */
name: string, 
/**
 * Transport kind (`"stdio"` | `"streamable_http"` | `"sse"` | `"auto"`).
 */
transport: string, 
/**
 * Optional log level override (passed to the server via
 * `logging/setLevel` post-init when supported).
 */
log_level?: string | null, };

// ─── McpServersDeleteParams.ts ────────────────────────────────────

/**
 * Params for `nexo/admin/mcp/delete`.
 */
export type McpServersDeleteParams = { 
/**
 * Server name to remove.
 */
name: string, };

// ─── McpServersDeleteResponse.ts ────────────────────────────────────

/**
 * Response for `nexo/admin/mcp/delete`.
 */
export type McpServersDeleteResponse = { 
/**
 * `true` when the entry was removed, `false` when the name
 * had no record (idempotent retry safe).
 */
removed: boolean, };

// ─── McpServersGetParams.ts ────────────────────────────────────

/**
 * Params for `nexo/admin/mcp/get`.
 */
export type McpServersGetParams = { 
/**
 * Server name to fetch.
 */
name: string, };

// ─── McpServersGetResponse.ts ────────────────────────────────────

/**
 * Response for `nexo/admin/mcp/get`. `server: None` is the
 * not-found case (daemon does NOT return an error so callers
 * can probe for existence cheaply).
 */
export type McpServersGetResponse = { 
/**
 * Matching server, or `None` when the name is unknown.
 */
server: McpServerDetail | null, };

// ─── McpServersListResponse.ts ────────────────────────────────────

/**
 * Response for `nexo/admin/mcp/list`.
 */
export type McpServersListResponse = { 
/**
 * Servers in stable alpha order by name.
 */
servers: Array<McpServerSummary>, };

// ─── McpServersUpsertResponse.ts ────────────────────────────────────

/**
 * Response for `nexo/admin/mcp/upsert`.
 */
export type McpServersUpsertResponse = { 
/**
 * Final server record after the write.
 */
server: McpServerDetail, 
/**
 * `true` when this call created a new server, `false` when
 * it updated an existing one (idempotent retry).
 */
created: boolean, };

// ─── MemoryEntryWire.ts ────────────────────────────────────

/**
 * One memory entry over the wire. Mirrors
 * `nexo_memory::MemoryEntry` minus internal-only fields.
 */
export type MemoryEntryWire = { 
/**
 * Stable UUID (string for wire stability).
 */
id: string, 
/**
 * Owning agent.
 */
agent_id: string, 
/**
 * Memory body (markdown / plain text).
 */
content: string, 
/**
 * Operator-set tags (`#user`, `#feedback`, etc.).
 */
tags: Array<string>, 
/**
 * Auto-derived concept tags.
 */
concept_tags: Array<string>, 
/**
 * ISO-8601 UTC timestamp of memory creation.
 */
created_at: string, 
/**
 * Memory type (User / Feedback / Project / Reference) —
 * drives per-type half-life decay in scoring.
 */
memory_type?: string | null, };

// ─── MemoryQueryParams.ts ────────────────────────────────────

/**
 * Params for `nexo/admin/memory/query`.
 */
export type MemoryQueryParams = { 
/**
 * Agent whose memory to search.
 */
agent_id: string, 
/**
 * Free-text query. Empty string returns the most recent
 * entries (recency wins when no query terms hit the FTS5
 * MATCH).
 */
query: string, 
/**
 * Max rows to return. Server-side clamp [1, 100], default 20.
 */
limit: number, };

// ─── MemoryQueryResponse.ts ────────────────────────────────────

/**
 * Response for `nexo/admin/memory/query`.
 */
export type MemoryQueryResponse = { 
/**
 * Matching entries newest-first within the relevance band.
 */
entries: Array<MemoryEntryWire>, };

// ─── MemorySnapshotsCreateParams.ts ────────────────────────────────────

/**
 * Params for `nexo/admin/memory/create_snapshot`.
 *
 * `encrypt` is a server-resolved toggle: the daemon picks the
 * recipient from `memory.snapshot.encryption.recipients[0]`. The
 * wire never carries the recipient string itself — clients can't
 * inject keys, and operators rotate recipients via YAML.
 */
export type MemorySnapshotsCreateParams = { 
/**
 * Agent whose memory to snapshot.
 */
agent_id: string, 
/**
 * Tenant scope. Empty string = "default" (consistent with
 * list/delete coercion).
 */
tenant: string, 
/**
 * Optional human-readable label stored in the bundle's
 * manifest (`pre-deploy`, `before-migration`, …).
 */
label?: string | null, 
/**
 * `true` requests age encryption. Server rejects with
 * `InvalidParams` when `true` and recipients are empty.
 */
encrypt: boolean, };

// ─── MemorySnapshotsCreateResponse.ts ────────────────────────────────────

/**
 * Response for `nexo/admin/memory/create_snapshot`.
 */
export type MemorySnapshotsCreateResponse = { 
/**
 * Metadata of the freshly captured bundle. Same shape as
 * `list_snapshots` entries so the SPA can append directly to
 * its in-memory list without a refetch.
 */
snapshot: SnapshotMetaWire, };

// ─── MemorySnapshotsDeleteParams.ts ────────────────────────────────────

/**
 * Params for `nexo/admin/memory/delete_snapshot`.
 */
export type MemorySnapshotsDeleteParams = { 
/**
 * Owning agent. Snapshots are partitioned by agent_id, so a
 * rogue id can't delete another agent's bundle.
 */
agent_id: string, 
/**
 * Tenant scope. Empty string = "default".
 */
tenant: string, 
/**
 * Snapshot id (UUID-shaped) to remove.
 */
id: string, };

// ─── MemorySnapshotsDeleteResponse.ts ────────────────────────────────────

/**
 * Response for `nexo/admin/memory/delete_snapshot`.
 */
export type MemorySnapshotsDeleteResponse = { 
/**
 * `true` when the bundle was removed; idempotent retry safe
 * (returns `true` on missing id too — daemon's local-fs
 * delete is `Ok(())` for already-gone bundles).
 */
removed: boolean, };

// ─── MemorySnapshotsListParams.ts ────────────────────────────────────

/**
 * Params for `nexo/admin/memory/list_snapshots`.
 */
export type MemorySnapshotsListParams = { 
/**
 * Agent whose snapshots to list.
 */
agent_id: string, 
/**
 * Tenant scope. Empty string = "default".
 */
tenant: string, };

// ─── MemorySnapshotsListResponse.ts ────────────────────────────────────

/**
 * Response for `nexo/admin/memory/list_snapshots`.
 *
 * SHAPE NOTE (0.1.12):
 * the `snapshots` field is unchanged but the response gained
 * `encryption_available`. Older clients that previously
 * deserialized the response as `Vec<SnapshotMetaWire>` directly
 * will need to update — the wire is now a struct. The
 * `serde(default)` on `encryption_available` keeps newer clients
 * hitting older daemons functional (flag defaults to `false`,
 * disabling the create-modal encrypt toggle).
 */
export type MemorySnapshotsListResponse = { 
/**
 * Snapshots ordered by `created_at_ms` descending (newest first).
 */
snapshots: Array<SnapshotMetaWire>, 
/**
 * `true` iff `memory.snapshot.encryption.enabled` AND
 * `recipients` non-empty at boot. Drives the encrypt toggle
 * availability in the create-snapshot modal so operators
 * don't try to encrypt without a recipient.
 */
encryption_available: boolean, };

// ─── MemorySnapshotsRestoreParams.ts ────────────────────────────────────

/**
 * Params for `nexo/admin/memory/restore_snapshot`.
 *
 * Restore by `snapshot_id` (NOT `bundle_path`): the daemon
 * resolves the absolute path via its `list()` lookup, so
 * admin endpoints can't be coerced into reading arbitrary
 * files. `tenant` is REQUIRED — the server cross-checks it
 * against the bundle manifest's recorded tenant and rejects
 * mismatches before touching disk.
 */
export type MemorySnapshotsRestoreParams = { 
/**
 * Agent whose state to restore.
 */
agent_id: string, 
/**
 * Tenant scope. REQUIRED — server validates against the
 * bundle manifest's recorded tenant; mismatch =
 * `InvalidParams` (defensive intent against accidental
 * cross-tenant restore).
 */
tenant: string, 
/**
 * Snapshot id (UUID-shaped). Server resolves to bundle
 * path via `list()` lookup; client never sees fs paths.
 */
snapshot_id: string, 
/**
 * `true` returns the diff that would be applied without
 * mutating live state. Default `false` = destructive.
 * Even when `true`, the daemon still validates tenant +
 * resolves the bundle so the preview reflects the real
 * restore plan.
 */
dry_run: boolean, };

// ─── MemorySnapshotsRestoreResponse.ts ────────────────────────────────────

/**
 * Response for `nexo/admin/memory/restore_snapshot`.
 */
export type MemorySnapshotsRestoreResponse = { 
/**
 * Per-restore report. SPA uses this to render the dry-run
 * preview table and the post-apply confirmation toast.
 */
report: RestoreReportWire, };

// ─── MicroappError.ts ────────────────────────────────────

/**
 * Notification payload.
 */
export type MicroappError = { 
/**
 * Operator-facing extension id (`extensions.yaml.entries.<id>`).
 */
microapp_id: string, 
/**
 * Discriminator for the four canonical error categories.
 */
kind: MicroappErrorKind, 
/**
 * JSON-RPC `id` that triggered the error, when applicable.
 * `None` for `Exit` (no in-flight call) and for boot-time
 * failures.
 */
correlation_id?: string | null, 
/**
 * UTC wall-clock at which the daemon observed the error.
 */
occurred_at: string, 
/**
 * One-line human-readable summary surfaced in the admin-ui
 * hover tooltip and Prometheus annotations. Keep terse —
 * stack trace goes in `stack_trace`.
 */
summary: string, 
/**
 * Optional multi-line stack trace / traceback. Bounded by
 * the daemon's stdio reader (16 KiB cap by convention) so
 * a runaway microapp can't blow up the broker.
 */
stack_trace?: string | null, };

// ─── MicroappErrorKind.ts ────────────────────────────────────

/**
 * Kind discriminator. `#[non_exhaustive]` so future kinds
 * (e.g. a `RateLimitTripped` once a respawn-throttle ships)
 * can land non-major.
 */
export type MicroappErrorKind = "init_timeout" | "handler_panic" | "exit" | "capability_denied";

// ─── OutboundReplyContext.ts ────────────────────────────────────

/**
 * Context the framework hands transformers + channel plugins for
 * every outbound reply. Read-only.
 */
export type OutboundReplyContext = { 
/**
 * Stable agent id producing the reply.
 */
agent_id: string, 
/**
 * Session UUID stringified.
 */
session_id: string, 
/**
 * `whatsapp` / `telegram` / `email` / etc.
 */
channel: string, 
/**
 * Plugin instance discriminator (e.g. `smoketest`,
 * `sucursal-norte`). `None` for single-instance channels.
 */
instance?: string | null, 
/**
 * Channel-native recipient address (whatsapp jid, telegram
 * chat_id, …). Optional because some pipelines (e.g. system-
 * injected ticks) don't have one yet.
 */
recipient?: string | null, 
/**
 * Tenant id when the agent is tenant-scoped, otherwise `None`.
 */
tenant_id?: string | null, 
/**
 * Conversation key used by operator UIs to group messages —
 * matches the one the firehose store + chat sidebar use
 * (`<agent_id>:session:<session_id>` for transcript-keyed
 * chats). Microapps key per-conversation state on this.
 */
conversation_key: string, 
/**
 * ISO-639-1 hint from `agents.yaml.<id>.language`. Lets reply
 * transformers localise their behaviour (e.g. voice_mode
 * picks a region-appropriate Edge voice when the operator
 * hasn't manually overridden it).
 */
language?: string | null, };

// ─── PairingChannelField.ts ────────────────────────────────────

/**
 * One field inside a `Form`-flow modal.
 */
export type PairingChannelField = { 
/**
 * Stable key (submitted to `credentials/register` verbatim).
 */
name: string, 
/**
 * Operator-visible label.
 */
label: string, 
/**
 * Inline help text.
 */
help?: string | null, 
/**
 * `true` ⇒ render as `<input type="password">`.
 */
sensitive: boolean, 
/**
 * Optional placeholder text.
 */
placeholder?: string | null, 
/**
 * Admin blocks submit until the operator types a non-empty
 * value.
 */
required: boolean, };

// ─── PairingChannelInfo.ts ────────────────────────────────────

/**
 * One pair-able channel as exposed to the admin.
 */
export type PairingChannelInfo = { 
/**
 * Stable channel id — matches `PairingStartInput::channel`
 * verbatim. Typically equals the plugin id.
 */
channel: string, 
/**
 * Pairing flow kind. Drives which modal branch the admin
 * renders.
 */
kind: PairingChannelKind, 
/**
 * Operator-visible label (`[plugin.pairing] label`, falling
 * back to `plugin.name`).
 */
label: string, 
/**
 * Locale-resolved instruction text. Empty string when the
 * plugin did not ship any instructions block — the admin
 * renders nothing in that case.
 */
instructions: string, 
/**
 * Form-flow only — field descriptors to render inside the
 * modal. Empty for the other kinds.
 */
fields?: Array<PairingChannelField>, 
/**
 * Instances already linked (matched against `credentials/list`).
 * Empty = channel has no credentials registered yet.
 */
linked_instances?: Array<string>, 
/**
 * Custom-flow only — JSON-RPC notify method the admin should
 * subscribe to (`nexo/notify/<rpc_namespace>/status_changed`).
 * `None` for non-custom kinds.
 */
notify_method?: string | null, 
/**
 * Phase 81.30 follow-up #4 — name of the form field whose
 * value the admin should treat as the credential `instance`
 * when calling `credentials/register`. `None` ⇒ the admin
 * falls back to the literal `"instance"`. Only populated
 * when `kind = "form"` and the plugin declared it.
 */
instance_field?: string | null, };

// ─── PairingChannelKind.ts ────────────────────────────────────

/**
 * Pairing flow kind — wire mirror of
 * `nexo_plugin_manifest::PairingKind`. Kept as a separate enum
 * so the wire crate doesn't depend on `nexo-plugin-manifest`.
 */
export type PairingChannelKind = "qr" | "form" | "info" | "custom";

// ─── PairingChannelsRequest.ts ────────────────────────────────────

/**
 * Params for `nexo/admin/pairing/channels`.
 *
 * Currently only carries an optional BCP-47 locale tag used to
 * resolve the operator-visible `instructions` string. Future
 * filters (tenant scope, plugin id allowlist) land here without
 * breaking the wire envelope.
 */
export type PairingChannelsRequest = { 
/**
 * BCP-47 locale tag (`"es"`, `"en"`, `"pt-BR"`). When `None`
 * the handler defaults to `"en"`. Resolution rule:
 * exact match → base language → `"en"` → first entry.
 */
locale?: string | null, };

// ─── PairingChannelsResponse.ts ────────────────────────────────────

/**
 * Response for `nexo/admin/pairing/channels`.
 *
 * Channels are returned ordered by plugin id ascending so the
 * admin UI stays stable across refreshes.
 */
export type PairingChannelsResponse = { 
/**
 * All channels exposed by the loaded plugins, joined with
 * credential state.
 */
channels: Array<PairingChannelInfo>, };

// ─── PersonaLocaleEntry.ts ────────────────────────────────────

/**
 * One `(locale, snapshot)` pair inside [`PersonaLocales::snapshots`].
 */
export type PersonaLocaleEntry = { 
/**
 * BCP-47 locale tag matching one entry in
 * [`PersonaLocales::available`].
 */
locale: string, 
/**
 * Snapshot of the persona content for this locale.
 */
snapshot: PersonaSnapshot, 
/**
 * Phase 81.31 follow-up #2 — recommended Microsoft Edge
 * neural voice id for this locale (e.g. `"es-AR-ElenaNeural"`,
 * `"en-US-AriaNeural"`). Sourced from
 * `nexo_tool_meta::locale::default_voice_for_locale`. `None`
 * when the daemon couldn't parse the locale or no voice is
 * mapped. Surfaced read-only — operator overrides via the
 * per-conversation voice mode tool, not via this field.
 */
recommended_voice?: string | null, };

// ─── PersonaLocales.ts ────────────────────────────────────

/**
 * Catalog of localised persona variants for one agent. Returned
 * inside [`crate::admin::agents::AgentDetail::persona_locales`].
 */
export type PersonaLocales = { 
/**
 * Ordered BCP-47 locale tags. First entry is the agent's
 * configured `language` (fallback `"en"`); remaining entries
 * are alpha-sorted. Always non-empty.
 */
available: Array<string>, 
/**
 * Per-locale snapshot of the agent's persona content.
 * Implemented as a `Vec<(locale, snapshot)>` so the wire
 * stays an ordered list (matches `available`) without needing
 * the admin to re-sort.
 */
snapshots: Array<PersonaLocaleEntry>, };

// ─── PersonaSaveLocalizedRequest.ts ────────────────────────────────────

/**
 * Params for `nexo/admin/persona/save_localized`.
 */
export type PersonaSaveLocalizedRequest = { 
/**
 * Target agent id. Must exist in `agents.yaml` (or a
 * persona-shipped `agents.d/*.yaml`).
 */
agent_id: string, 
/**
 * BCP-47 locale tag. Validated server-side via
 * `nexo_tool_meta::locale::Locale::from_str` before any
 * filesystem write.
 */
locale: string, 
/**
 * New system_prompt for this locale. Written into
 * `agents.d/<id>.yaml::locale_prompts[locale]` when
 * `patch_yaml` is true.
 */
system_prompt: string, 
/**
 * New `IDENTITY.<locale>.md` content.
 */
identity: string, 
/**
 * New `SOUL.<locale>.md` content.
 */
soul: string, 
/**
 * New `USER.<locale>.md` content.
 */
user: string, 
/**
 * New `AGENTS.<locale>.md` content.
 */
agents: string, 
/**
 * When `true` (default), the daemon patches
 * `agents.d/<id>.yaml::locale_prompts[locale]` after writing
 * the four workspace files. Set `false` when the caller
 * already manages the YAML separately (avoids a double-write
 * race when followed by `agents/upsert`).
 */
patch_yaml: boolean, };

// ─── PersonaSaveLocalizedResponse.ts ────────────────────────────────────

/**
 * Response shape for `nexo/admin/persona/save_localized`.
 */
export type PersonaSaveLocalizedResponse = { 
/**
 * Absolute paths of files successfully written, in write
 * order. Useful for rollback by the caller and for audit
 * logging.
 */
written_paths: Array<string>, 
/**
 * Updated [`PersonaLocales`] reflecting the new locale.
 * Lets the admin refresh its dropdown without a second
 * `agents/get` roundtrip.
 */
persona_locales: PersonaLocales, };

// ─── PersonaSnapshot.ts ────────────────────────────────────

/**
 * Snapshot of one agent's persona content at a specific locale.
 *
 * Empty strings indicate the file is absent on disk AND no
 * fallback is available; admin renders "(not localized)" hints
 * for files not in [`Self::present_files`].
 */
export type PersonaSnapshot = { 
/**
 * Resolved system prompt (from `locale_prompts[locale]` or
 * the top-level `system_prompt` fallback).
 */
system_prompt: string, 
/**
 * Content of `<workspace>/IDENTITY[.<locale>].md`.
 */
identity: string, 
/**
 * Content of `<workspace>/SOUL[.<locale>].md`.
 */
soul: string, 
/**
 * Content of `<workspace>/USER[.<locale>].md`.
 */
user: string, 
/**
 * Content of `<workspace>/AGENTS[.<locale>].md`.
 */
agents: string, 
/**
 * Subset of `{"system_prompt","identity","soul","user","agents"}`
 * whose source actually exists for this locale (either as a
 * locale-suffixed file or — for non-default locales — falling
 * back to the unsuffixed file). Used by the admin to render
 * "(not localized)" hints.
 */
present_files?: Array<string>, };

// ─── PluginCategory.ts ────────────────────────────────────

/**
 * Functional bucket auto-derived from `nexo-plugin.toml` sections
 * at fetch time. Manifest sections are introspected per Phase
 * 81.33.b.real auto-discovery design — discovery never asks
 * authors to tag manually.
 */
export type PluginCategory = "channel" | "poller" | "webhook" | "persona" | "tool" | "unknown";

// ─── PluginSource.ts ────────────────────────────────────

/**
 * Where a `DiscoveredPlugin` was found. A single plugin may
 * appear in multiple sources; the catalogue merges them so the
 * operator sees "available on crates.io + indexed" badges.
 */
export type PluginSource = { "kind": "crates_io" } | { "kind": "github_topic", 
/**
 * `<org>/<name>` slug — used to build the manifest URL.
 */
repo: string, } | { "kind": "curated_index" };

// ─── PluginsCompatCheckParams.ts ────────────────────────────────────

/**
 * Params for `nexo/admin/plugins/compat_check`.
 */
export type PluginsCompatCheckParams = { 
/**
 * crates.io crate name (e.g. `nexo-plugin-telegram`).
 * Validated against the same `[a-z0-9_-]` char class
 * `plugin_install` enforces.
 */
crate_name: string, 
/**
 * Optional pinned version. `None` → latest published.
 */
version?: string | null, };

// ─── PluginsCompatCheckResponse.ts ────────────────────────────────────

/**
 * Response for `nexo/admin/plugins/compat_check`.
 */
export type PluginsCompatCheckResponse = { 
/**
 * Compat result against the running daemon's SDK version.
 */
compat: CompatStatus, 
/**
 * Parsed manifest summary when fetch succeeded. `None` when
 * the manifest URL returned 404 / parse error.
 */
manifest_summary?: ManifestSummary | null, };

// ─── PluginsDoctorResponse.ts ────────────────────────────────────

/**
 * Response for `nexo/admin/plugins/doctor`.
 */
export type PluginsDoctorResponse = { 
/**
 * Full `PluginDiscoveryReport` JSON. Identical to what the
 * `agent doctor plugins --json` CLI emits — a stable wire
 * shape (`doctor_render::render_json`).
 */
report: JsonValue, 
/**
 * Server-side wall-clock when the report was built (ms
 * since epoch). Operators see this as a "as of …" hint.
 */
generated_at_ms: number, };

// ─── PluginsInstallParams.ts ────────────────────────────────────

/**
 * Params for `nexo/admin/plugins/install`.
 *
 * Two delivery paths governed by [`InstallSource`]:
 *   - `Release` (default): download prebuilt binary from GitHub
 *     releases following cargo-dist URL convention.
 *   - `Cargo`: shell out to `cargo install <crate>` (compiles
 *     locally; requires rustc).
 *
 * Sealed against arbitrary command injection — the `crate_name` is
 * validated as a crates.io identifier (`[a-z0-9_-]+`), `version`
 * against a semver-ish pattern, and `repo` against a `<org>/<name>`
 * GitHub-slug pattern before any spawn or HTTP request.
 */
export type PluginsInstallParams = { 
/**
 * crates.io package name (e.g. `nexo-plugin-telegram`).
 * Rejected if non-empty chars outside `[a-z0-9_-]`.
 */
crate_name: string, 
/**
 * Optional pinned version. `None` resolves to the latest
 * published release. Rejected if non-empty chars outside
 * `[0-9A-Za-z.+-]`. REQUIRED for `source = Release` (we don't
 * query GitHub's "latest release" endpoint to keep the daemon
 * hermetic + offline-friendly).
 */
version?: string | null, 
/**
 * GitHub repo slug (`org/name`) hosting the release artefacts.
 * REQUIRED for `source = Release`. Ignored for `Cargo`.
 * Defaults to `lordmacu/<crate_name>` if not supplied — the
 * convention for first-party Nexo plugins.
 */
repo?: string | null, 
/**
 * Delivery channel. See [`InstallSource`] docs.
 */
source: InstallSource, 
/**
 * `force = true` passes `--force` to `cargo install` (Cargo
 * path) OR overwrites the existing binary (Release path).
 * Default `false` skips when the version is already current.
 */
force: boolean, 
/**
 * Phase 98.4 — parity with `nexo plugin install --require-signature`.
 * When `true` the silent installer escalates `[[authors]]` policy
 * to `Require` regardless of the TOML setting; an unsigned
 * release rejects with `PolicyRequiresSig`. Mutually exclusive
 * with `skip_signature_verify` — the admin handler rejects the
 * combination with `InvalidParams`. Ignored for
 * [`InstallSource::Cargo`] (cargo path doesn't expose the
 * release tarball signature surface; response will carry
 * `trust_enforcement = "cargo_skipped"`).
 */
require_signature: boolean, 
/**
 * Phase 98.4 — parity with `nexo plugin install --skip-signature-verify`.
 * Downgrades policy to `Ignore` regardless of TOML for this
 * install. Use case: SaaS operator needs to install an unsigned
 * pre-release plugin from a known dev. Mutually exclusive with
 * `require_signature` — admin handler rejects the combo.
 */
skip_signature_verify: boolean, };

// ─── PluginsInstallResponse.ts ────────────────────────────────────

/**
 * Response for `nexo/admin/plugins/install`.
 */
export type PluginsInstallResponse = { 
/**
 * Echo of the crate the operator asked for.
 */
crate_name: string, 
/**
 * Version actually installed (parsed from `cargo install`
 * stdout, or echoed from the `version` param when supplied).
 * `None` when the install succeeded but the version couldn't
 * be parsed back.
 */
installed_version?: string | null, 
/**
 * Plugin ids hot-spawned in the same call (the rescan that
 * runs after `cargo install` returns). Usually one entry, but
 * can be empty if the operator already had the binary on disk
 * and just wanted the daemon to scan, or multiple if a single
 * crate ships several `nexo-plugin-*` binaries.
 */
spawned: Array<string>, 
/**
 * Trimmed `cargo install` stdout for operator forensics. Long
 * outputs are clipped to ~16 KiB so the JSON reply stays sane.
 */
cargo_stdout: string, 
/**
 * Trimmed `cargo install` stderr — Cargo prints progress here.
 */
cargo_stderr: string, 
/**
 * Phase 98.4 — discriminator for how trust policy was applied:
 *   - `"policy_applied"` — Release path; `trusted_keys.toml`
 *     policy resolved + enforced normally.
 *   - `"user_require"` — Release path; operator forced
 *     `require_signature = true` in params.
 *   - `"user_skip"` — Release path; operator forced
 *     `skip_signature_verify = true` in params.
 *   - `"cargo_skipped"` — Cargo source; signature surface
 *     unavailable so trust enforcement deferred.
 */
trust_enforcement: string, 
/**
 * Phase 98.4 — Gap 3.1 closed. `true` when cosign verified the
 * release tarball; `false` for Cargo path or unsigned Release.
 */
signature_verified: boolean, 
/**
 * Phase 98.4 — SAN extracted from cosign cert (e.g. GitHub
 * Actions workflow URL). `None` when verification skipped.
 */
signature_identity?: string | null, 
/**
 * Phase 98.4 — OIDC issuer the cert was minted by. `None` when
 * verification skipped.
 */
signature_issuer?: string | null, 
/**
 * Phase 98.4 — effective trust mode that ran for this install
 * (`"ignore" | "warn" | "require"`). Empty string for Cargo
 * source.
 */
trust_mode: string, 
/**
 * Phase 98.4 — `[[authors]]` entry that matched the release
 * owner (if any). `None` means the owner had no policy entry
 * and the global default was applied.
 */
trust_policy_matched?: string | null, };

// ─── PluginsRefreshIndexParams.ts ────────────────────────────────────

/**
 * Params for `nexo/admin/plugins/refresh_index`. Empty — the
 * daemon invalidates its disk cache and re-fetches every source.
 */
export type PluginsRefreshIndexParams = Record<symbol, never>;

// ─── PluginsRefreshIndexResponse.ts ────────────────────────────────────

/**
 * Response for `nexo/admin/plugins/refresh_index`.
 */
export type PluginsRefreshIndexResponse = { 
/**
 * Number of unique `DiscoveredPlugin` entries after merge.
 */
items_count: number, 
/**
 * Source names that succeeded.
 */
sources_ok: Array<string>, 
/**
 * Source names that failed + reasons.
 */
sources_err: Array<SourceError>, };

// ─── PluginsRestartParams.ts ────────────────────────────────────

/**
 * Params for `nexo/admin/plugins/restart`.
 */
export type PluginsRestartParams = { 
/**
 * Plugin id from the manifest's `[plugin] id` field. Must
 * match a discovered subprocess plugin or the daemon
 * returns `InvalidParams { "plugin {id} not found" }`.
 * In-tree plugins return `InvalidParams { "plugin {id} is
 * in-tree, restart not applicable" }` — operators restart
 * the daemon for those.
 */
plugin_id: string, };

// ─── PluginsRestartResponse.ts ────────────────────────────────────

/**
 * Response for `nexo/admin/memory/restart`.
 */
export type PluginsRestartResponse = { 
/**
 * Echo of the plugin id for client-side correlation.
 */
plugin_id: string, 
/**
 * Wallclock duration the previous `Inner` survived between
 * last spawn (initial init or last respawn) and the manual
 * restart. Operator forensics value: "this child lived 3
 * minutes before I had to restart".
 */
previous_uptime_ms: number, 
/**
 * Wallclock millis since epoch when the new `Inner` was
 * installed. Audit log correlation.
 */
restarted_at_ms: number, 
/**
 * PID of the freshly spawned child. Operator dashboards can
 * correlate with `ps`/`top` output. `None` when the
 * post-spawn shutdown race-check kicked in (very rare;
 * indicates the daemon shut down between the spawn
 * completing and the install).
 */
new_pid?: number | null, };

// ─── PluginsScanParams.ts ────────────────────────────────────

/**
 * Params for `nexo/admin/plugins/scan`. Empty for now; the daemon
 * re-runs its configured discovery walker and reports diffs.
 */
export type PluginsScanParams = Record<symbol, never>;

// ─── PluginsScanResponse.ts ────────────────────────────────────

/**
 * Response for `nexo/admin/plugins/scan`.
 */
export type PluginsScanResponse = { 
/**
 * Plugin ids the daemon discovered that were NOT in the live
 * registry before the scan. Each was hot-spawned and is now
 * reachable via the dispatcher, pairing trigger registry, and
 * admin router. Order: discovery walk order.
 */
spawned: Array<string>, 
/**
 * Plugin ids the daemon found in the live registry that no
 * longer have a discoverable manifest (binary deleted, search
 * path removed, etc.). They are NOT auto-uninstalled — the
 * operator must explicitly call `plugins/uninstall`. This list
 * is purely informative so the UI can surface "stale" badges.
 */
stale: Array<string>, 
/**
 * Free-form per-plugin scan diagnostics — manifest validation
 * failures, duplicate-id collisions, capability denials. Keyed
 * by plugin id when known, else by manifest file path.
 */
warnings: Array<string>, };

// ─── PluginsSearchParams.ts ────────────────────────────────────

/**
 * Params for `nexo/admin/plugins/search`.
 */
export type PluginsSearchParams = { 
/**
 * Optional substring filter applied client-side post-merge
 * against `name + description + tags`. `None` → return the
 * full catalogue (paginated naturally by source caps).
 */
query?: string | null, 
/**
 * When `true`, drop entries where `compat` is `NeedsUpgrade` /
 * `Incompatible`. Keeps `Unknown` (manifest fetch failed —
 * not necessarily incompatible).
 */
compat_only: boolean, 
/**
 * Optional category filter (`channel`, `poller`, `tool`,
 * `webhook`, `persona`). `None` → all.
 */
category?: string | null, 
/**
 * Optional source filter (`crates_io`, `github_topic`,
 * `curated_index`). `None` → all sources.
 */
source?: string | null, };

// ─── PluginsSearchResponse.ts ────────────────────────────────────

/**
 * Response for `nexo/admin/plugins/search`.
 */
export type PluginsSearchResponse = { 
/**
 * Merged + filtered catalogue. Empty when every source is
 * down or rate-limited — `partial_failures` then carries the
 * per-source errors.
 */
items: Array<DiscoveredPlugin>, 
/**
 * Unix milliseconds when the underlying catalogue was last
 * refreshed (cache hit = older value; cold fetch = "now").
 * Drives the "Updated <X> ago" footer on the UI.
 */
fetched_at_ms: number, 
/**
 * One entry per source that failed; healthy sources contribute
 * to `items` regardless. Empty when every source succeeded.
 */
partial_failures: Array<SourceError>, };

// ─── PluginsSetEnabledParams.ts ────────────────────────────────────

/**
 * Params for `nexo/admin/plugins/set_enabled`. Toggles a plugin's
 * enabled state by editing `plugins/discovery.yaml`'s
 * `discovery.disabled[]` list + hot-removing (disable) or
 * hot-spawning (enable) the live handle. Unlike `uninstall`, the
 * on-disk binary is never deleted — re-enabling re-spawns it with
 * no re-download.
 */
export type PluginsSetEnabledParams = { 
/**
 * Plugin id from the manifest's `[plugin] id`.
 */
plugin_id: string, 
/**
 * `true` → enable (remove from `disabled[]` + hot-spawn).
 * `false` → disable (append to `disabled[]` + hot-remove).
 */
enabled: boolean, };

// ─── PluginsSetEnabledResponse.ts ────────────────────────────────────

/**
 * Response for `nexo/admin/plugins/set_enabled`.
 */
export type PluginsSetEnabledResponse = { 
/**
 * Echo of the plugin id.
 */
plugin_id: string, 
/**
 * Echo of the requested enabled state.
 */
enabled: boolean, 
/**
 * `true` when `discovery.yaml` actually changed. `false` when
 * the plugin was already in the requested state (idempotent).
 */
config_changed: boolean, 
/**
 * On enable: plugin ids hot-spawned (usually one). Empty on
 * disable.
 */
spawned: Array<string>, 
/**
 * On disable: `true` when the live handle was dropped. `false`
 * on enable or when no handle existed.
 */
removed: boolean, 
/**
 * Free-form per-plugin diagnostics from the spawn/remove cycle
 * (init failures, register errors). Empty on the happy path.
 */
warnings: Array<string>, };

// ─── PluginsUninstallParams.ts ────────────────────────────────────

/**
 * Params for `nexo/admin/plugins/uninstall`.
 */
export type PluginsUninstallParams = { 
/**
 * Plugin id from the manifest's `[plugin] id`. The daemon
 * stops the subprocess, drops the handle from the live
 * registry, and (when `cargo_uninstall = true`) shells out to
 * `cargo uninstall <crate_name>` so the binary leaves disk.
 */
plugin_id: string, 
/**
 * When `true`, also runs `cargo uninstall <crate_name>` where
 * `crate_name` is derived from the plugin's manifest
 * `[plugin.cargo].crate_name` field, or the operator's
 * override. `false` (default) keeps the binary on disk so the
 * operator can re-enable later without a fresh download.
 */
cargo_uninstall: boolean, 
/**
 * Optional explicit crate name when the manifest doesn't
 * declare `[plugin.cargo].crate_name`. Ignored when
 * `cargo_uninstall = false`.
 */
crate_name?: string | null, };

// ─── PluginsUninstallResponse.ts ────────────────────────────────────

/**
 * Response for `nexo/admin/plugins/uninstall`.
 */
export type PluginsUninstallResponse = { 
/**
 * Echo of the plugin id.
 */
plugin_id: string, 
/**
 * `true` when the plugin was stopped and dropped from the
 * registry. `false` when no such plugin existed (idempotent).
 */
removed: boolean, 
/**
 * `true` when `cargo uninstall` also ran successfully. `false`
 * when not requested OR when cargo uninstall failed (the
 * in-process removal still succeeded; the operator gets a
 * warning in `cargo_stderr`).
 */
cargo_uninstalled: boolean, 
/**
 * Trimmed cargo stdout when `cargo_uninstall = true`.
 */
cargo_stdout?: string, 
/**
 * Trimmed cargo stderr when `cargo_uninstall = true`.
 */
cargo_stderr?: string, };

// ─── ProcessingControlState.ts ────────────────────────────────────

/**
 * Persisted control state for one scope. `AgentActive` is the
 * default — every scope starts in this state and the store
 * only allocates a row once an operator pauses it.
 */
export type ProcessingControlState = { "state": "agent_active" } | { "state": "paused_by_operator", 
/**
 * Echo of the scope so callers reading state alone
 * have the discriminator handy.
 */
scope: ProcessingScope, 
/**
 * Epoch ms when the pause was set.
 */
paused_at_ms: number, 
/**
 * `token_hash` of the operator's bearer so audits can
 * correlate without storing the
 * cleartext token.
 */
operator_token_hash: string, 
/**
 * Free-form reason. Optional.
 */
reason?: string | null, };

// ─── ProcessingScope.ts ────────────────────────────────────

/**
 * Scope the operator is suspending (or operating on).
 * `#[non_exhaustive]` so adding new agent shapes later is
 * non-breaking. v0 only routes `Conversation` end-to-end;
 * other variants are accepted on the wire but the dispatcher
 * returns `-32601 not_implemented`.
 */
export type ProcessingScope = { "kind": "conversation", 
/**
 * Owning agent.
 */
agent_id: string, 
/**
 * Channel plugin (e.g. `whatsapp`).
 */
channel: string, 
/**
 * Channel-side account id (e.g. WA business id).
 */
account_id: string, 
/**
 * Counterparty id (e.g. WA jid).
 */
contact_id: string, 
/**
 * Populated when the conversation
 * arrived via an MCP channel server (e.g. `slack`).
 * `None` for native-channel inbounds.
 */
mcp_channel_source?: string | null, } | { "kind": "agent_binding", 
/**
 * Owning agent.
 */
agent_id: string, 
/**
 * Channel plugin.
 */
channel: string, 
/**
 * Channel-side account id.
 */
account_id: string, } | { "kind": "agent", 
/**
 * Agent id.
 */
agent_id: string, } | { "kind": "event_stream", 
/**
 * Owning agent.
 */
agent_id: string, 
/**
 * Subject glob.
 */
subject_pattern: string, } | { "kind": "batch_queue", 
/**
 * Owning agent.
 */
agent_id: string, 
/**
 * Queue name.
 */
queue_name: string, } | { "kind": "custom", 
/**
 * Owning agent.
 */
agent_id: string, 
/**
 * Caller-defined scope discriminator.
 */
scope_kind: string, 
/**
 * Caller-defined scope id.
 */
scope_id: string, };

// ─── ResolvedBy.ts ────────────────────────────────────

/**
 * How a previously-pending escalation was settled.
 */
export type ResolvedBy = { "kind": "operator_takeover" } | { "kind": "operator_dismissed", 
/**
 * Free-form reason — kept for the audit log.
 */
reason: string, } | { "kind": "agent_resolved" };

// ─── RestoreReportWire.ts ────────────────────────────────────

/**
 * Wire-side projection of `nexo_memory_snapshot::RestoreReport`.
 * `AgentId` and `SnapshotId` flatten to strings for forward
 * compatibility (the wire stays stable if the runtime swaps
 * id encodings).
 */
export type RestoreReportWire = { 
/**
 * Agent the restore targeted.
 */
agent_id: string, 
/**
 * Snapshot id the bundle was restored from.
 */
from_snapshot_id: string, 
/**
 * Auto-captured pre-restore snapshot id. `None` for
 * dry-run (no pre-snapshot is taken when nothing mutates).
 * Production restore path forces `auto_pre_snapshot=true`
 * server-side so this is always populated for destructive
 * runs.
 */
pre_snapshot_id?: string | null, 
/**
 * HEAD oid the memdir was reset to, when git capture was
 * active. `None` when the snapshot didn't carry a git body
 * (small / state-only bundles).
 */
git_reset_oid?: string | null, 
/**
 * SQLite databases that were restored (filenames, not
 * absolute paths — the SPA lists them in the report panel).
 */
sqlite_restored_dbs: Array<string>, 
/**
 * State files (`extract_cursor`, `last_dream_run`, …) that
 * were restored.
 */
state_files_restored: Array<string>, 
/**
 * `true` if the daemon paused + restarted agent workers as
 * part of the restore (always `true` for destructive runs;
 * `false` for dry-run).
 */
workers_restarted: boolean, 
/**
 * Mirror of the request's `dry_run` for the SPA to render
 * "Preview" vs "Applied" headers without round-tripping
 * state.
 */
dry_run: boolean, };

// ─── SecurityEventKind.ts ────────────────────────────────────

/**
 * Security-domain audit events. Nested under
 * [`AgentEventKind::SecurityEvent`] so subscribers persist
 * every variant alongside transcript / escalation events for
 * a unified audit log.
 */
export type SecurityEventKind = { "security_kind": "token_rotated", 
/**
 * Epoch milliseconds when the rotation persisted.
 */
at_ms: number, 
/**
 * Previous operator-token-hash (16-char sha256-hex
 * prefix). Zeroed (`""`) for the very first rotation
 * after boot when no prior hash is in cache.
 */
prev_hash: string, 
/**
 * New operator-token-hash.
 */
new_hash: string, 
/**
 * Optional operator-supplied audit hint, capped to
 * `auth::REASON_MAX_LEN` chars by the handler.
 */
reason?: string | null, };

// ─── SnapshotMetaWire.ts ────────────────────────────────────

/**
 * Wire-side projection of `nexo_memory_snapshot::SnapshotMeta`.
 * Internal fields (bundle_path, schema_versions, git_oid)
 * surfaced as opaque strings for forward-compat.
 */
export type SnapshotMetaWire = { 
/**
 * Snapshot id (UUID-shaped string).
 */
id: string, 
/**
 * Owning agent.
 */
agent_id: string, 
/**
 * Tenant scope.
 */
tenant: string, 
/**
 * Optional human-readable label set at create time.
 */
label?: string | null, 
/**
 * Wall-clock millis since epoch when the bundle was written.
 */
created_at_ms: number, 
/**
 * Absolute filesystem path of the bundle archive.
 */
bundle_path: string, 
/**
 * Bundle size in bytes (after compression / encryption).
 */
bundle_size_bytes: number, 
/**
 * Hex-encoded SHA-256 of the bundle.
 */
bundle_sha256: string, 
/**
 * `Some(oid)` when git-mode snapshots captured a commit.
 */
git_oid?: string | null, 
/**
 * True when the bundle is age-encrypted (`*.tar.zst.age`).
 */
encrypted: boolean, 
/**
 * True when redaction policies stripped fields at capture time.
 */
redactions_applied: boolean, };

// ─── SourceError.ts ────────────────────────────────────

/**
 * Per-source failure surfaced to the UI's
 * `<PartialFailureBanner>`. `search` returns whatever items the
 * healthy sources produced + this list of failures, so a
 * rate-limited GitHub doesn't blank the page.
 */
export type SourceError = { 
/**
 * Source name (`crates_io`, `github_topic`, `curated_index`).
 */
source: string, 
/**
 * Human-readable failure reason. Already escaped for label
 * rendering; ≤ 256 chars.
 */
message: string, };

// ─── TranscriptRole.ts ────────────────────────────────────

/**
 * Speaker role mirror — kept on the wire side so SDK types
 * don't pull in the core crate. Matches
 * `nexo_core::agent::transcripts::TranscriptRole`.
 */
export type TranscriptRole = "user" | "assistant" | "tool" | "system";

// ─── TrustTier.ts ────────────────────────────────────

/**
 * Operator-facing trust signal derived from owner allowlist +
 * curated index membership. Never enforced here — install
 * continues to route through Phase 97.1 signature verification.
 */
export type TrustTier = "official" | "community_indexed" | "unverified";

// ─── WebhookEnvelope.ts ────────────────────────────────────

/**
 * Typed JSON envelope nexo publishes after every accepted
 * webhook request.
 *
 * Subscribers correlate events via `envelope_id` (deterministic
 * dedup) and `received_at_ms` (late-binding analytics).
 * `headers_subset` is a defensive allowlist — secrets like
 * `Authorization` / `Cookie` / signature headers are stripped
 * before publish, so a NATS subscriber sees only non-secret
 * correlation IDs.
 *
 * Unlike [`crate::BindingContext`], this struct is intentionally
 * *not* `#[non_exhaustive]`: it represents a wire-shape value
 * constructed on both sides (the daemon writes it; tests +
 * mocks build it via struct-literal). Field additions are
 * semver-major because the JSON wire shape changes regardless.
 *
 * # Example
 *
 * Microapps typically deserialise the envelope from a NATS
 * payload:
 *
 * ```
 * use nexo_tool_meta::WebhookEnvelope;
 *
 * let payload = serde_json::json!({
 *     "schema": 1,
 *     "source_id": "github_main",
 *     "event_kind": "pull_request",
 *     "body_json": {"action": "opened"},
 *     "headers_subset": {},
 *     "received_at_ms": 0,
 *     "envelope_id": "00000000-0000-0000-0000-000000000000",
 *     "client_ip": null
 * });
 * let env: WebhookEnvelope = serde_json::from_value(payload).unwrap();
 * assert_eq!(env.schema, 1);
 * assert_eq!(env.source_id, "github_main");
 * ```
 */
export type WebhookEnvelope = { 
/**
 * Wire-shape version. Always [`ENVELOPE_SCHEMA_VERSION`].
 */
schema: number, 
/**
 * Operator-assigned source identifier — matches the
 * `webhook_receiver.sources[].id` YAML field.
 */
source_id: string, 
/**
 * Event kind extracted from the inbound request (header or
 * JSON body path, per source config).
 */
event_kind: string, 
/**
 * Inbound body, parsed as JSON. Non-JSON bodies are wrapped
 * as `{ "raw_base64": "..." }` upstream.
 */
body_json: JsonValue, 
/**
 * Allowlisted headers forwarded for downstream correlation.
 * Authorization / Cookie / signature headers are stripped.
 */
headers_subset: { [key in string]: string }, 
/**
 * Server-side receipt timestamp in milliseconds since epoch.
 */
received_at_ms: number, 
/**
 * Random per-envelope identifier — useful for dedup.
 */
envelope_id: string, 
/**
 * Resolved client IP (after trusted-proxy logic). `None`
 * for envelopes built outside an HTTP request context.
 */
client_ip: string | null, };
